### ISSUE TITLE
Question: Does miniFab support deployment in a Kubernetes cluster in AWS EKS and Azure AKS?

### ISSUE THREAD

**Issue by nileshdeotale** [hyperledger-labs/minifabric#106]
I am planning to deploy fabric network in AWS EKS (Amazon Kuberenetes service) and Azure Kubernetes service. Does miniFab support deployment for this?
If yes, appreciate if you could share details on how to achieve this. Thanks!

**Comment by litong01** [comment]
Minifabric only deploys to physical or virtual machine environment running Windows 10, Linux or OS X. It wont deploy onto K8S env. If you have AWS virtual machines, it will work.

**Comment by nileshdeotale** [comment]
thanks @litong01.  Is there any plan to support K8s env in near future? Similar to hfrd, taking kubeconfig as an input?

**Comment by litong01** [comment]
I was thinking about it but need some contributions from others

**Comment by ryjones** [comment]
could this build on cello?

**Comment by litong01** [comment]
In theory yes. But cello's k8s support has been outdated.

**Comment by davidkhala** [comment]
Per my overview, I think another lab project BAF is a closer answer to this question
https://github.com/hyperledger-labs/blockchain-automation-framework

**Comment by nileshdeotale** [comment]
thanks @litong01 @davidkhala , This does seem to be the way to go https://github.com/hyperledger-labs/blockchain-automation-framework . I will try this.

**Comment by litong01** [comment]
@nileshdeotale in that case, can you please close this issue?
