### ISSUE TITLE
Question: Could you provide more documentation on how to deploy the minifabric in multiple servers? 

### ISSUE THREAD

**Issue by wuyg1226** [hyperledger-labs/minifabric#112]
Dear Professor Li,
Thank you very much for sharing this very good automation tool to deploy fabric network so easily. I am new to hyperledger fabric. I watched your video and readme document. I know minifabric can do the following things:
1. deploy Fabric networks across multiple servers or VMs
2. can depoly multi-channel Fabric networks (one peer joins in several channels with different chaincode)
 3.  use the minifab to join all them together to make a bigger Fabric network.
Could you give me some detailed information about how to achieve them? such as the steps and commands we should use? 
For example, for the first task "1. deploy Fabric networks across multiple servers or VMs". when i use the command "./minifab netup ", it will start up all the nodes based on spec.yaml on one machine. How could i control it to start up the nodes on different machines? Thank you very much for your time.

Best Wishes,
Ying Wu

**Comment by pkirkinezis** [comment]
The documentation to add another org from another network exist . There should be no difference in mutliple , more than 3  .
You have to netup both servers of both vm's making sure that one can talk to another . 
There is a detailed video on youtube if you read the docs on section youtube video .
Then you apply the same for 4 -5-6. 

The only black spot is the channelsign , channelupdate . You have to undestant the difference between endorsement policies and application group versioning when joining new peers from other servers.

**Comment by wuyg1226** [comment]
Dear pkirkinezis,
Thank you very much for your reply. Now i understand what you mean after watching the video on adding a new organisation.  So deploying multi-channel Fabric networks on multiple VMs, what i should do is: 
1. setup a blockchain network with channel1 on VM1 with spec.yaml, installing chaincode1 on the peers in channel1 (org1, org2).  
2. setup another blockchain network with channel2 on VM2 with another spec.yaml , installing chaincode2 on the peers in channel2 (org 3, org 4)  . 
3.  add  org3 to channel1 to make sure org3 join in two channels (channel1 and channel2). 
4. after adding org3 to channel1, just following the steps on" bring in peers(org3) to the channel1" to install chaincode1 onto org3's peers. 
5. after these steps, peers in org3 belong to two channels and have been installed two chaincodes. 
Am I right? Thank you.
Best Wishes,
Ying Wu

**Comment by litong01** [comment]
@wuyg1226 it is largely correct. Basically, you start with a small network (regardless how many orgs or peers), then you use netup to stand up another org with its peers, it does not matter too much if you install any particular chaincode onto the new peers, you can totally skip installing the chaincode step. once your org is part of a channel, also please read this document on how to expand your network with chaincode handling. https://github.com/hyperledger-labs/minifabric/blob/master/docs/ExpandYourNetwork.md

In the doc, it gives you some instructions on how to take advantages of discovery services as well.

**Comment by litong01** [comment]
@wuyg1226 Please also close this issue since this is more of a question rather than an issue against minifabric. Also, you can take advantages of rocket chat channel #fabric-mini for more questions or help.

**Comment by wuyg1226** [comment]
Dear Professor Li,
Thank you very much for your response and further explanation ^_^. I will close it and i will use chat channel for help in the future. Thank you again.
Best Wishes,
Ying Wu
