### ISSUE TITLE
Service Discovery error: failed constructing descriptor for chaincode.

### ISSUE THREAD

**Issue by edkaz** [hyperledger-labs/minifabric#118]
Hello 

I'm posting this issue here just in case it affects the _minifab_ community but have also posted to the fabric community. 

We have been developing a web based application on Hyper-ledger Fabric using the Node SDK (fabric-network v2.2.3 and fabric-protos v2.2.0). We use the fabric contract API (fabric-contract-api v2.3.0 and fabric-shim 2.3.0). I have a running fabric network of four nodes, an order and a CA running on Apple Macs and the same configuration running on a Centos 7.7 server (both on SE Linux and regular Linux) all deployed with _minifab_.  

I can verify that gateway object is created and instantiated, and that the network and contract objects are created and are defined. However, regardless of the system running the fabric network I keep getting the following service discovery error:

2020-11-08T05:19:05.609Z - error: [DiscoveryService]: send[my-chaincode] - Channel:mychannel received discovery error:failed constructing descriptor for chaincodes:<name:"my-chaincode">

My understanding is that a similar problem has been fixed in Fabric version 2.2.1 (Release notes tagged FAB-18191 release 2.2.1) but we are still seeing this error come every time we run test cases. 

__System Configuration:__

*  Containers:                    
    fabric-peer:2.2.1   (I'm assuming this is Fabric version 2.2.1) 
                                fabric-orderer:2.2.1
                                      fabric-ca:1.4

*  Operating Systems:      
    Centos   7.7
                                      Darwin   10.15.7
* Node SDK:                   
     fabric-network v2.2.3
                                        fabric-contract-api v2.3.0
                                        fabric-shim 2.3.0

I don't know if this is a _minifab_ problem or not but I do know that we have only started seeing this error recently. Can you help?

Thanks - Ed

**Comment by litong01** [comment]
@edkaz what action did you take when you saw the errors? When you invoke simple or samplecc chaincode, are you seeing same errors?

**Comment by edkaz** [comment]
@litong01

**Comment by edkaz** [comment]
@litong01 Hello - again I don't know if this is not relevant to minifab or not. I have tested our chain code using ```minifab invoke``` using a selection of chain code invocations and have never seen this error _Service Discovery_.  My understanding is that if a transaction is sent via the CLI then the CLI bypasses the new service discovery features.  I've also tested sending transactions to the chain code on earlier versions but can't remember which version right now - again no error.

**Comment by edkaz** [comment]
@litong01 In fact I've used _minifab_ quite a bit to help debug our chain code.

**Comment by edkaz** [comment]
@litong01 I'm sorry, I should have said that I used ```fabric-network``` and ```fabric-contract``` node SDK to make the call to the running fabric.

**Comment by litong01** [comment]
@edkaz I've developed test code in go to test things. it was written in go and included in minifabric, you can simply run `minifab apprun` if you have samplecc chaincode installed, approved and committed. that app is in app/go directory using gosdk gateway, I believe it is using dynamic service discovery as well. Please take a look at that and make changes to in vars/app directory to whatever you like, then run `minifab apprun` again, your new code will run. I've been using that to test various things, you can try it as well. Also I believe caliper is using the dynamic discovery, minifabric support `minifab caliperrun` which again is using the samplecc, you can try that as well. I believe caliper is using node js to do things.

**Comment by litong01** [comment]
@edkaz your transaction did not go through right? When you run caliperrun with explorerup, you can actually see transactions coming through from explorer user interface. another thing you will have to do is to setup anchor node for your channel. Without anchor node, dynamic service discovery wont work.

**Comment by litong01** [comment]
@edkaz I setup a network and run caliperrun with explorerup, everything worked as expected and not seeing any errors like you described in the caliper log file.

**Comment by edkaz** [comment]
@litong01 Hello I think you are ahead of me where _apprun_ and _calliper_ are involved and I've been using older stuff like ```docker logs``` and ```logspout``` to track container activity.  I will do as you suggest and see if that is more enlightening. If this is okay with you I will keep this comment open for another day or two until I test everything out, but my suspicion is that its fabric. We use the node js contract API to connect to the running fabric and chain code.

**Comment by pkirkinezis** [comment]
Thre is something called Discovery service  if i got your concept right. https://hyperledger-fabric.readthedocs.io/en/release-2.2/discovery-overview.html

@edkaz As @litong01  said you have to setup anchor peers across all your machines and then join them to any channel and chaincodes. Then  Discovery service knows where to ask for endorsement if needed .

Another way of doing that without anchor peers is to create a custom channel  node config including all the peer nodes of the channel . This config file if included on  your api gateway in case of any transaction will ask all the endorsing peers with setting like above : 
 "endorsingPeer": true
        "chaincodeQuery": true
        "eventSource": true

Keep in ming by deafult (without anchor peers on your network) if you run "minifab profilegen -c channel_name" on one of your machines the config file produced will only include the peers nodes of that machine and that machine only. Also the endorsment file will have nothing inside. Only the orderer file will have the orderer because you run "minifab nodeimport"
