### ISSUE TITLE
Minifab up with goproxy.cn works but apprun failed

### ISSUE THREAD

**Issue by malajisi** [hyperledger-labs/minifabric#133]
I modified spec.yaml and uncomment GOPROXY line, **minifab up** works fine, and the chaincode simple container startup. But it break on **minifab apprun** step. Does the two have two different config file? Thanks.

<img width="987" alt="image" src="https://user-images.githubusercontent.com/1553205/100245016-8c351b80-2f72-11eb-90dc-84ca800f025a.png">

**Comment by litong01** [comment]
That means app run also need to use the go proxy which is not done currently. Can you submit a PR to fix it?

**Comment by malajisi** [comment]
Okay, let me try~

**Comment by malajisi** [comment]
Have submitted and fix in PR https://github.com/hyperledger-labs/minifabric/pull/135#issue-528171925.
