### ISSUE TITLE
minifab join step fails for extending the network

### ISSUE THREAD

**Issue by SaurabhVatsa** [hyperledger-labs/minifabric#134]
Followed the exact steps from https://github.com/hyperledger-labs/minifabric/blob/master/docs/ExpandYourNetwork.md
When joining the channel from the new organization in site1, the step ```minifab nodeimport,join``` fails.

Environment:
Two different EC2 instances as site0 and site 1

Error
```
# Running operation: ******************************************
  channel join
.......
# Run the channel join script on cli container ****************
  non-zero return code
  Error: failed to create deliver client for orderer: orderer client failed to connect to 176.12.45.2037203: failed to create new connection: context deadline exceeded
  2020-11-26 11:00:44.899 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: genesis block file not found open /vars/mychannel.genesis.block: no such file or directory

# STATS *******************************************************
minifab: ok=25	failed=1
```
The same issue has been detected when following video tutorials.

**Comment by litong01** [comment]
Not sure how your ip can be 176.12.45.2037203, can you check if you are using right parameters setting up network?

**Comment by litong01** [comment]
Are you missing something in your configuration or copy paste failed, the address looks bad.

**Comment by litong01** [comment]
Also, you probably need to make sure two instances can communicate with each other. Mini fabric have not been tested on aws env. The network connectivity is the key.

**Comment by SaurabhVatsa** [comment]
> Not sure how your ip can be 176.12.45.2037203, can you check if you are using right parameters setting up network?

That was a copy mistake. My bad.
Had to make sure the instances talk to each other. That fixed it.

**Comment by litong01** [comment]
If it fixed your problem ,can you close this?
