### ISSUE TITLE
avoid downloading gradle every time I deploy

### ISSUE THREAD

**Issue by Mavlarn** [hyperledger-labs/minifabric#140]
Hi, I am dosing some contract developing, and need to deploy the contract many times. But every time when I install a contract, it will start a docker and download the gradle zip file. Is there any way do avoid to download it every time?

Thanks.

**Comment by litong01** [comment]
I assume that your chaincode was developed using Java. Regardless what language you use , this is how fabric deals with chaincode. I think you can package your chaincode as tar ball and place it in the vars/chaincode/<chaincode name> directory with a naming convention that minifabric follows, that way I think you can avoid building it. In any case, this has nothing to do with minifabric. I think you can close this issue.
