### ISSUE TITLE
allcouchdbs is undefined when setting up the network.

### ISSUE THREAD

**Issue by Akayeshmantha** [hyperledger-labs/minifabric#142]
Hi All 

When I try to up the network with the below command 

`./minifab up -o nimble.efpf.com -e true -s couchdb`

I am getting an error `'allcouchdbs' is undefined`

Any idea ?

**Comment by litong01** [comment]
Wonder if you use latest code. Please run minifab update command , then minifab cleanup. Then try again. I just tried it and had no issues.

**Comment by litong01** [comment]
@Akayeshmantha I've tested using your command. it all worked fine. As I indicated above, please do run the following commands in sequence.

```
./minifab cleanup
./minifab update
./minifab up -o nimble.efpf.com -e true -s couchdb
```
