### ISSUE TITLE
error: adding multiple organizations

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#144]
I tried adding organizations according to docs/ExpandYourNetwork.md.

adding 1st organization(orgx) is succeeded
but adding 2nd organization(orgy)  fails always by ENDORSEMENT_POLICY_FAILURE at 'minifab commit' operation.

```shell
cat ~/mysite0/spec.yaml

fabric:
  peers:
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"

cat ~/mysite1/spec.yaml

fabric:
  peers:
  - "peer1.orgx.example.com"
  - "peer2.orgx.example.com"

cat ~/mysite2/spec.yaml

fabric:
  peers:
  - "peer1.orgy.example.com"
  - "peer2.orgy.example.com"
```
```shell
# operations for adding 1st organization (the same as docs/ExpandYourNetwork.md)
# starts operations for adding 2nd organization (named orgy)
$ cd ~/mysite2
$ minifab netup   -e 7400 -o orgy.example.com
$ sudo cp   ~/mysite2/vars/JoinRequest_orgy-example-com.json   ~/mysite0/vars/NewOrgJoinRequest.json
: 
: # operations according to docs/ExpandYourNetwork.md between ~/mysite0  and ~/mysite2
:
$ cd ~/mysite0
$ minifab approve,commit
Using spec file: ~/mysite0/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=samplecc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS=
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=7000
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=ipaddress
    WORKING_DIRECTORY: ~/mysite0

# Preparing for the following operations: *********************
  verify options, cc approve, cc commit
# Running operation: ******************************************
  verify options
# Running operation: ******************************************
  cc approve
# Running operation: ******************************************
  cc commit
# Run the chaincode commit script on cli container ************
  non-zero return code
  2021-01-22 02:06:53.055 UTC [chaincodeCmd] ClientWait -> INFO 001 txid [f79834f807ef806a3ef0e5438f016fb10b5df0e974a15fca1f2032927553c211] committed with status (ENDORSEMENT_POLICY_FAILURE) at ipaddress:7000
  2021-01-22 02:06:53.078 UTC [chaincodeCmd] ClientWait -> INFO 002 txid [f79834f807ef806a3ef0e5438f016fb10b5df0e974a15fca1f2032927553c211] committed with status (ENDORSEMENT_POLICY_FAILURE) at ipaddress:7002
  Error: transaction invalidated with status (ENDORSEMENT_POLICY_FAILURE)

# STATS *******************************************************
minifab: ok=37  failed=1"

```

**Comment by litong01** [comment]
@itaru2622 are these sites on the same machine or different machines? seems to me that there are quite few steps missed such as what you have done on the `mysite0`, `mysite1` etc, please list every step that you took. please do not assume that others somehow know what you have tried and how to get the error. So anyone takes your reproducing process can recreate your error.

**Comment by itaru2622** [comment]
@litong01 thank you for your response.

I tested all sites on the same machine. my full operations were described bellow.
```
# fist, exactly the same operations in docs/ExpandYourNetwork.md (setup mysite0 and mysite1)
:
# after all operations done in docs/ExpandYourNetwork.md, start bellow.
# my operations for adding 2nd organization(orgy) based on the docs/ExpandYourNetwork.md

cd ~/mysite2
minifab netup -e 7400 -o orgy.example.com

cd ~/mysite0
sudo cp ~/mysite2/vars/JoinRequest_orgy-example-com.json ~/mysite0/vars/NewOrgJoinRequest.json
minifab orgjoin

cd ~/mysite2
sudo cp ~/mysite0/vars/profiles/endpoints.yaml vars
minifab nodeimport,join

cd ~/mysite2
minifab install,approve -n samplecc -p ''

# starts additional approve operation by mysite1
cd ~/mysite1
minifab approve
# ends additional approve operation by mysite1
# result (ENDORSEMENT_POLICY_FAILURE) was the same, even I omitted above additional approve operation

cd ~/mysite0
minifab approve,commit

# get ENDORSEMENT_POLICY_FAILURE here.

cd ~/mysite2
minifab discover
minifab stats
```

**Comment by pkirkinezis** [comment]
You propably have to set endorsers manually or you have to check if anchir peers are setup. 
I would suggest you to go to /discover folder and check the channel/ endorsment file to see if all organizations exists . 
Commit command uses the samplecc_endorsers.json to ask all the necesery peers and commit anything . 
So run discover command on the channel that samplecc chaincode is installed and post the json here to check

**Comment by itaru2622** [comment]
@pkirkinezis Thank you for your response.

when should I execute discover on which site?

As described in docs/ExpandYourNetwork.md,
when I finished adding first organization, I did 'minifab discover'  and found that orgx was in ./vars/discover/mychannel/samplecc_endorsers.json... (I will post json if need)

**Comment by litong01** [comment]
you can do discover any time on every site, it wont hurt anything.

Tong Li
IBM Open Technology

**Comment by itaru2622** [comment]
hmm, the result was changed when I add 'minifab discover'just before the last 'minifab commit' in site0 (referenced point 0). I got success. 
```bash
# my new operation after reference point0

cd ~/mysite0
minifab approve,discover # reference point 0 (changed from approve,commit)

cd ~/mysite1
minifab discover # this may be omit-able, not sure

cd ~/mysite2
minifab discover # this may be omit-able, not sure

cd ~/mysite0
minifab commit # got success !!!

cd ~/mysite0
minifab discover # result is attached, as samplecc_endorsers_mysite0.txt

cd ~/mysite1
minifab discover # result is attached, as samplecc_endorsers_mysite1.txt

cd ~/mysite2
minifab discover # refer is attached, as samplecc_endorsers_mysite2.txt
```
even commit command was succeeded, I found the result of discover were different between sites( when I added orgx, all sites got the same result, i.e. all sites found all endorsement points).
As you can see in the files, 
- mysite0 discovered all endorsement points, [samplecc_endorsers_mysite0.txt](https://github.com/hyperledger-labs/minifabric/files/5888725/samplecc_endorsers_mysite0.txt)

- mysites1 could not find orgy, [samplecc_endorsers_mysite1.txt](https://github.com/hyperledger-labs/minifabric/files/5888728/samplecc_endorsers_mysite1.txt)

- mysite2 could not find orgx,  [samplecc_endorsers_mysite2.txt](https://github.com/hyperledger-labs/minifabric/files/5888739/samplecc_endorsers_mysite2.txt)

- Layout are also different between sites.

I'm not sure if the above discovering results were expected results or not...
I'm afraid if later chaincode invoke command may get failure...

**Comment by itaru2622** [comment]
@pkirkinezis @litong01  what should I do for the next action?

**Comment by pkirkinezis** [comment]
What do you mean with what you should do next? 
To see if they are the expected results   depends on your channel config . In the docs you can see Li tong has you tube videos.
They are a bit outdated by today implementation but Li tong explains in detail how channel config works and affects endorsers.
Probably invoke will get a failure if you are not asking the endorsers needed.

**Comment by itaru2622** [comment]
@pkirkinezis thank you for your comment.
I will watch videos and check how should I operate for adding multiple organizations, and also test chain code transactions.

**Comment by itaru2622** [comment]
@pkirkinezis @litong01

I could succeed chaincode transactions on the environment built by the above operation, even each site has some difference in samplecc_endorsers.json

bellow is operations for adding second organization(orgY)

```shell
cd ~/mysite2
minifab netup -e 7400 -o orgy.example.com

cd ~/mysite0
sudo cp ~/mysite2/vars/JoinRequest_orgy-example-com.json ~/mysite0/vars/NewOrgJoinRequest.json
minifab orgjoin

cd ~/mysite2
sudo cp ~/mysite0/vars/profiles/endpoints.yaml vars
minifab nodeimport,join

cd ~/mysite2
minifab install,approve -n samplecc -p ''

# additional approve by mysite1 (orgX)
cd ~/mysite1
minifab approve

# additional discover needed between approve and commit on mysite0
cd ~/mysite0
minifab approve,discover,commit

cd ~/mysite2
minifab discover
minifab stats
```

I think it is good to change docs/ExpandYourNetwork.md as follows:
```patch
cd ~/mysite0
- minifab approve,commit
+ minifab approve,discover,commit
```
