### ISSUE TITLE
Is there a way to define a new consortium or a new channel profile after the network is up using "netup" ?

### ISSUE THREAD

**Issue by anilhelvaci** [hyperledger-labs/minifabric#152]

**Comment by pkirkinezis** [comment]
This is not an issue we can discuss in more detail  here https://chat.hyperledger.org/channel/fabric-mini.
To change channel configuration you need to update channel_config file generated my minifabric on the proccess of channel creation. 
To know exactly what is needed to be changed for your specific needs you need to read the documentation of hyperledger fabric .

**Comment by b21527084** [comment]
Thank you for your response 🙏 I asked this in the fabric-mini channel but could not get any answer from the admins so I thought I could ask here and label it as a question but then realized I am not allowed to label issues. Here are the steps I follow when try to define a new consortium:

- `minifab channelquery -c systemchannel`
- In systemchannel_config.json[channel_group][groups][Consortiums][groups] I add new consortium definition and increase the verion of "Consortiums" by 1
- `minifab channelsign,channelupdate`

Result: An error message about authorization failure and status code 500

I ran these commands on an organization so do you think this could be the problem? What if I ran these commands using 
`-o {orderder name}` ? Could it work?

**Comment by pkirkinezis** [comment]
Sorry for no responding to the chat .I only tested once to add new peers to existing system channel consortium without any issues .

**Comment by litong01** [comment]
Minifabric does not allow you to change or add a new consortium after your network has been up running. I do not think currently any tool will allow you to do that or fabric itself supports such function.

**Comment by b21527084** [comment]
I see. Thank you for your answer. What about defining a new channel profile? Is it possible to define a new channel profile once the network is up?

**Comment by litong01** [comment]
`minifab create -c whatevername` will create a new channel. please read the docs in docs directory.

**Comment by b21527084** [comment]
I am aware that `minifab create -c whatevername` can be used for creating a new channel. What I meant was that if I create a new channel using `minifab create -c whatevername` every organization in the network is included in the channel( _the ones in the spec.yaml file_ ) because it is based on `--profile OrgChannel`. I want to separate my organizations. In order to do that I thought I should define a new channel profile under "Profiles" section of configtx.yaml. I am able to do that if I change the configtx.yaml before the network is up. What I am wondering is whether there is a way to update configtx.yaml file and define new channel profiles after the network is up or not?

**Comment by litong01** [comment]
You should not need to modify configtx ever. Initially you work with spec.yaml when you work with minifabric, once system is up running any changes necessary to a channel is done via channel update. If you are not using minifabric to stand up your network, then you will need to make changes to configtx before you use some tool to bootstrap your system, even that is not always the case, but again once your system is up running, this file is no longer used. Please read fabric docs to get a good understanding of fabric concept.

**Comment by litong01** [comment]
closing due to no activities.
