### ISSUE TITLE
Error to add a secondo new organisation

### ISSUE THREAD

**Issue by ivanv6** [hyperledger-labs/minifabric#161]
Hi, i'm working to add new organisation inside a Fabric network. The first org is the default, the second one has the following specs:

> 
>fabric:
>   peers:
>   - "peer1.orgx.example.com"
>   - "peer2.orgx.example.com"

Now, i'm trying to add a new org with the following specs:

> fabric:
>   peers:
>   - "peer1.orgy.example.com"
>   - "peer2.orgy.example.com"
>   orderers:
>   - "orderer4.example.com"

But when i run the command:

`minifab.cmd nodeimport,join`

on the new folder, i received the following error:

```
# Run the channel join script on cli container ****************
  non-zero return code
  2021-02-15 18:07:30.155 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  2021-02-15 18:07:30.159 UTC [cli.common] readBlock -> INFO 002 Expect block, but got status: &{NOT_FOUND}
  Error: can't read the block: &{NOT_FOUND}
  2021-02-15 18:07:30.307 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: genesis block file not found open /vars/mychannel.genesis.block: no such file or directory

# STATS *******************************************************
minifab: ok=34  failed=1
```

How can i handle it? Another question, there is a way to trigger the chaincode if the first node is down? This should be a typical case of a blockchain. Thanks a lot

**Comment by litong01** [comment]
you will have to use orgjoin command to join the new org to the network first, then join the peer node to channel. Join org and peer node to a network are different things. please look at the docs before you open issue.

**Comment by ivanv6** [comment]
Hi @litong01 , i already run the orgjoin command on the First network with success. As you can read, one organisation is already connected. The issue Is not solved

**Comment by litong01** [comment]
as I have said, you need to join the orgy to the fabric network first, then you can join the channel. From your report, it does not look like you have done that orgjoin. please provide very detailed steps so that someone can possibly reproduce what you experienced.

**Comment by ivanv6** [comment]
Thanks @litong01 , i try to details all the steps.

First, I created the sample network ,called mynet0, as described in: [https://github.com/hyperledger-labs/minifabric/tree/master/docs](https://github.com/hyperledger-labs/minifabric/tree/master/docs). All the steps are successfull. Then, I added a new organization called mynet1, as reported here: [https://github.com/hyperledger-labs/minifabric/blob/master/docs/ExpandYourNetwork.md](https://github.com/hyperledger-labs/minifabric/blob/master/docs/ExpandYourNetwork.md) with the following _spec.yaml_:

> fabric:
> peers:
> 
> "peer1.orgx.example.com"
> "peer2.orgx.example.com"

Also here, the new peers are able to communicate on the chaincode successfully.
Now, I want to add a new organisation, called mynet2, with the following specs:

> fabric:
> peers:
> 
> "peer1.orgy.example.com"
> "peer2.orgy.example.com"
> orderers:
> "orderer4.example.com"
and the command: `minifab netup -e 7400 -o orgy.example.com`
Then i run:

`cd ~/mynet0`
`sudo cp ~/mynet2/vars/JoinRequest_orgx-example-com.json ~/mynet0/vars/NewOrgJoinRequest.json`
`minifab orgjoin`

This command works perfectly. Now when i run the commands:

`cd ~/mynet2`
`sudo cp ~/mynet0/vars/profiles/endpoints.yaml vars`
`minifab nodeimport,join`
the shell returns this error:

> # Run the channel join script on cli container ****************
>   non-zero return code
>   2021-02-15 18:07:30.155 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
>   2021-02-15 18:07:30.159 UTC [cli.common] readBlock -> INFO 002 Expect block, but got status: &{NOT_FOUND}
>   Error: can't read the block: &{NOT_FOUND}
>   2021-02-15 18:07:30.307 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
>   Error: genesis block file not found open /vars/mychannel.genesis.block: no such file or directory
> 
> # STATS *******************************************************
> minifab: ok=34  failed=1

My aim is to add a new organisation with an orderer (in this case, orderer4.example.com). Probably the issue is related to this new node on the network. How can I manage it? Also, how mynet1 is able to reach the new orderer?

**Comment by litong01** [comment]
The only thing I can think of not looking right is the 4th orderer node. Not really sure how the orderer node can be involved. If it is possible, I suggest that you remove the 4th orderer node and give it a try.

**Comment by ivanv6** [comment]
@litong01, if i removed the orderer, it works. But that's the point. I would like to add other orderers (for greater reliability and so on) and also to test and validate what happens if a node on the network disconnects from the network. For now, if the mynet0 node disconnects, nobody can communicate with the chaincode anymore. In theory, in blockchain systems, this shouldn't happen. The other nodes mynet1 and mynet2 should be able to communicate with each other and then synchronize when mynet0 connects to the internet again. If I understand correctly, this is done by orderers, so adding new orderers is essential for this magnificent tool.

**Comment by litong01** [comment]
adding orderer org and orderer nodes can be done by channel update command. The orgjoin and channel join command eventually all use channel update commands. Minifab does not have a command to do orderer org join or channel join. You could follow the steps on how to do a raw channel update, that is, use channelquery, then make changes to the return json file, then do channelsign, then channelupdate. It is quite involved but it can be done pretty much for any channel update.

**Comment by ivanv6** [comment]
@litong01 i tried by following you suggestion and also the video #3 but until now i have the same issue. I think should be useful to provide to the community a guide to add new orgs with orderer and a way to connect the orderers.

**Comment by litong01** [comment]
@ivanv6 both document and videos are provided for adding new organizations.
