### ISSUE TITLE
minifab channelsign,channelupdate hang up

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledger-labs/minifabric#162]
Hi minifabric,

I am going to upgrade channel setting via steps below, I hope to apply `minifabric/vars/systemchannel_config.json` to minifab. but it hangs up...

```  
   ./minifab up -i 2.2
   .... success
   ./minifab channelquery -c systemchannel
   ... success
    // modified minifabric/vars/systemchannel_config.json
   ./minifab channelsign,channelupdate -c systemchannel
   Using spec file: /Users/yuanyi/OpenSource/probe/Probe/minifabric/spec.yaml
  hang up
```
I am even added `-vvvv` in `minifabric/scripts/mainfuncs.sh` to enable ansible debug model.
but there nothing output.

**Comment by litong01** [comment]
Please close this one because this has nothing to do with minifabric.
