### ISSUE TITLE
Minifab fails when launching the network again

### ISSUE THREAD

**Issue by kilicbaran** [hyperledger-labs/minifabric#163]
### Expected Behavior
When the network is stopped (`minifab down`) and launched again (`minifab netup`) without changing the configurations, it should work.

### Current Behavior
When the network is stopped (`minifab down`) and launched again (`minifab netup`) without changing the configurations, it gives the following error:
```
...
# Create volumes for peer and orderer nodes *******************
  'allcouchdbs' is undefined

# STATS *******************************************************
minifab: ok=43	failed=1
```

### Steps to Reproduce
1. `minifab cleanup`
1. `minifab up`
1. `minifab down`
1. `minifab netup`

### Environment

Minifab version:
```
# Current Minifabric image ID and created at date time ********
  a69732ec2cf2   2021-02-07 20:22:19 +0000 UTC
```
Environment 1:
OS: Macos 10.14.6
Docker desktop: 3.1.0
Docker Engine: 20.10.2
gRPC FUSE feature is disabled.

Environment 2:
OS: Amazon linux 2
Docker version: 19.03.13-ce

I tried with these two environments. They both give this error.

**Comment by litong01** [comment]
@kilicbaran this is confirmed. I will provide a fix asap

**Comment by litong01** [comment]
@kilicbaran please verify with the latest build and close this issue when the latest resolved the issue.

**Comment by kilicbaran** [comment]
Thank you @litong01. Now, it works.
