### ISSUE TITLE
Is CA component used?

### ISSUE THREAD

**Issue by volodyad** [hyperledger-labs/minifabric#165]
As I see ca certs in created in step: "Create ca self signed certificate"
via "openssl req -new",  this certificates is used to create components MSP

But this ca certificates is no passed to the docker ca start command
(e.g. fabric-ca-server start -b admin:adminpw --cafiles ca/ca1/fabric-ca-config.yaml
--cafiles ca/ca2/fabric-ca-config.yaml )
It means that CA component cannot be used to enroll and register users for the blockchain network, 

Therefore I have a question, what is the usage of the CA component at the moment?

**Comment by pkirkinezis** [comment]
Hi @volodyad  ,
CA is used to control authorization and keyfiles when interacting with the blockchain.

I will try to describe what i do in my case so you can see a use case of CA authority. I use JAVA Gateway to interact with the blockchain for register, invoke ,query.

I choose not to use the keyfiles created by minifab for the admin user . So here are the  steps I've done throuth JAVA:

1. Enroll  the admin user (this step connects to CA authority and creates keyfiles for admin user)
2. Create a wallet/enrollment  for the admin user and save it on a database or physically a wallet on a filesystem path.
3. Use this admin wallet to Register a new user (Registers the user to CA authority )
4. Enroll the user after register to create a wallet/enrollment and save it to a path ( Connect to CA authority to create keyfiles for the new user )

Then you can use the new user wallet to interact with blockchain network if you want.

**Comment by litong01** [comment]
Please asking question in fabric-mini channel. closing this since this is not a minifabric issue.
