### ISSUE TITLE
Error adding wallets to vscode

### ISSUE THREAD

**Issue by FelipeSanchezCalzada** [hyperledger-labs/minifabric#168]
Basically i follow [this video.](https://www.youtube.com/watch?v=KMtz-0OGjZ8&list=PL0MZ85B_96CExhq0YdHLPS5cmSBvSmwyO&index=5)
I am trying to add the wallets to vscode and I am getting the following error:
`Error displaying Fabric Wallets: Cannot read property 'curve' of undefined`

The wallet file contains:
```
{ "name":"Admin",
  "mspid":"example-com",
  "role": null,
  "affiliation": "",
  "enrollmentSecret": "",
  "enrollment": {
     "signingIdentity": "9d08b55e4bc269f0b1bfc02c57c42c2a8e59df825d757cbb3155c17e259afa92",
     "identity": {"certificate": "-----BEGIN CERTIFICATE-----\nMIICMjCCAdigAwIBAgIUIdbxLUBNvPE8ZbZ1Dri2Ww3gTBcwCgYIKoZIzj0EAwIw\nZzELMAkGA1UEBhMCVVMxFzAVBgNVBAgMDk5vcnRoIENhcm9saW5hMRAwDgYDVQQH\nDAdSYWxlaWdoMRQwEgYDVQQKDAtleGFtcGxlLmNvbTEXMBUGA1UEAwwOY2EuZXhh\nbXBsZS5jb20wHhcNMjEwMjI1MTg1MTQwWhcNMzAxMTI1MTg1MTQwWjBkMQswCQYD\nVQQGEwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExEDAOBgNVBAcMB1JhbGVp\nZ2gxDjAMBgNVBAsMBWFkbWluMRowGAYDVQQDDBFBZG1pbkBleGFtcGxlLmNvbTBZ\nMBMGByqGSM49AgEGCCqGSM49AwEHA0IABFZcE1JYZhL/U6VfdzzBUHD3QmOtq4W8\nH4EWqzUqQCRulZOMyR3QB44GYaJ8RDc/SXIngCBiM2QE4CxGZZ0zu2+jZTBjMA4G\nA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8EAjAAMCIGA1UdEQQbMBmHBMCoAtWCEUFk\nbWluQGV4YW1wbGUuY29tMB8GA1UdIwQYMBaAFID5l9FKjkK1+dgSMMUXE+lHa6Zq\nMAoGCCqGSM49BAMCA0gAMEUCIQC0nOGnAWTwT4+HVA1E0axGoe8wGJGZ7gGf0tAp\nrmHhVwIgGdmp1uWntaGHBOYi+uPP0M24aG5AUQroYSLvfqS6Pck=\n-----END CERTIFICATE-----" }
  }
} 
```

To up network i do:
`./minifab up -i 1.4.5`

Versions:
```
IBM Blockchain Platform extension: v1.0.40
VS Code: v1.52.1
```

I need this version of IBM blockchain platform for debug my chaincode.

Thank you very much for the project, it is incredible

**Comment by litong01** [comment]
I think you may have a mismatch wallet and vs code extension. The latest vscode extension would need 2.x wallets.

**Comment by FelipeSanchezCalzada** [comment]
Thank you very much for responding quickly.
I don't use the latest version of the extension, I use 1.0.40, which supports debugging and works with fabric 1.4.x

**Comment by litong01** [comment]
@FelipeSanchezCalzada can you try the latest and see if it works with latest vscode entension? just to confirm.

**Comment by FelipeSanchezCalzada** [comment]
@litong01 sure, I update the version of IBM Blockchain Platform for the test to version v2.0.2 (latest) and now the error is the following:
`Failed to add a new wallet: Unknown identity type: HSM-X.509`

I have also tried with old versions from a year ago and I get the same error.

**Comment by litong01** [comment]
Both versions 1.4.x and 2.x have all been tested. The error looks very foreign to me. Are you using some hardware based store to save secrets?

**Comment by FelipeSanchezCalzada** [comment]
No, I am using a basic configuration for testing. 
I have tried to see the extension logs but there is nothing else, only the errors that I have already attached depending on the version. 
Thank you very much for your interest.

**Comment by litong01** [comment]
@FelipeSanchezCalzada is this still an issue? If not, please close, if yes, please add more details on how to recreate this with the following information:

1. How you start up minifabric
2. What os that you are running VSCode on?
3. What version of VSCode and fabric plugin were you using?
4. What are the errors specifically?

If no details provided, I intend to close this in few days. Thanks.

**Comment by litong01** [comment]
Closing with stale status.
