### ISSUE TITLE
`-e` option for peer port `7061`

### ISSUE THREAD

**Issue by davidkhala** [hyperledger-labs/minifabric#178]
I did some experiments and found no matter how I adjust the value of `--expose-endpoints`, it always start increment from `0.0.0.0:8779->7061/tcp`

How could I control this metric/operation purpose port 7061?

**Comment by litong01** [comment]
-e 6800 try that or any value greater than 1021

**Comment by davidkhala** [comment]
Per conversation, the second port of peer, exposed port of `peer:7061` is 1000 more than the exposed port map to `peer:7051` of same peer.

**Comment by litong01** [comment]
@davidkhala any update on this? If not, please close this.
