### ISSUE TITLE
CouchDB issue

### ISSUE THREAD

**Issue by ivanv6** [hyperledger-labs/minifabric#185]
I implemented a network based on couchdb by exposing port 7000. When i browse the page:

`http://127.0.0.1:7008/mychannel`

it returns to me the following error:

`{"error":"not_found","reason":"Database does not exist."}`

How can i manage this issue? Moreover, how can i set up credential to use Fauxton to accesso CouchDB information?

Here my configuration:

`CONTAINER ID   IMAGE                               COMMAND                   CREATED              STATUS                    PORTS                                            NAMES
37e3faad4f0d   hyperledger/fabric-tools:2.3.0      "/bin/sh"                 44 seconds ago       Up 42 seconds                                                              00c7aeb68c_cli
bb88948a66d5   hyperledger/fabric-ca:1.4           "/bin/sh -c 'fabric-…"    46 seconds ago       Up 44 seconds             0.0.0.0:7001->7054/tcp                           ca1.org1.example.com
3b9d02754506   hyperledger/fabric-ca:1.4           "/bin/sh -c 'fabric-…"    48 seconds ago       Up 45 seconds             0.0.0.0:7000->7054/tcp                           ca1.org0.example.com
28377916bd54   hyperledger/fabric-orderer:2.3.0    "orderer"                 50 seconds ago       Up 47 seconds             0.0.0.0:7012->7050/tcp, 0.0.0.0:8012->7060/tcp   orderer3.example.com
d65ed0e3679e   hyperledger/fabric-orderer:2.3.0    "orderer"                 52 seconds ago       Up 49 seconds             0.0.0.0:7011->7050/tcp, 0.0.0.0:8011->7060/tcp   orderer2.example.com
ad652dc73f7e   hyperledger/fabric-ccenv:2.3        "/bin/sh -c '\nset -e…"   53 seconds ago       Up 50 seconds                                                              nifty_bose
eff5face5981   hyperledger/fabric-orderer:2.3.0    "orderer"                 54 seconds ago       Up 51 seconds             0.0.0.0:7010->7050/tcp, 0.0.0.0:8010->7060/tcp   orderer1.example.com
f944d8d36513   hyperledger/fabric-ccenv:2.3        "/bin/sh -c '\nset -e…"   55 seconds ago       Up 52 seconds                                                              sweet_murdock
7bc6a2f12708   hyperledger/fabric-peer:2.3.0       "peer node start"         56 seconds ago       Up 54 seconds             0.0.0.0:7005->7051/tcp, 0.0.0.0:8005->7061/tcp   peer2.org1.example.com
813904e7a00c   hyperledger/fabric-ccenv:2.3        "/bin/sh -c '\nset -e…"   57 seconds ago       Up 54 seconds                                                              infallible_zhukovsky
6c66e9f6aa6f   hyperledger/fabric-peer:2.3.0       "peer node start"         58 seconds ago       Up 55 seconds             0.0.0.0:7004->7051/tcp, 0.0.0.0:8004->7061/tcp   peer1.org1.example.com
e9837f9d222a   hyperledger/fabric-ccenv:2.3        "/bin/sh -c '\nset -e…"   58 seconds ago       Exited (0) 1 second ago                                                    thirsty_shamir
b926f03c728c   hyperledger/fabric-peer:2.3.0       "peer node start"         58 seconds ago       Up 56 seconds             0.0.0.0:7003->7051/tcp, 0.0.0.0:8003->7061/tcp   peer2.org0.example.com
373a43f12604   hyperledger/fabric-peer:2.3.0       "peer node start"         About a minute ago   Up 57 seconds             0.0.0.0:7002->7051/tcp, 0.0.0.0:8002->7061/tcp   peer1.org0.example.com
b6248699ea1d   hyperledger/fabric-couchdb:latest   "tini -- /docker-ent…"    About a minute ago   Up 58 seconds             4369/tcp, 9100/tcp, 0.0.0.0:7009->5984/tcp       peer2.org1.example.com.couchdb
73aa367addf6   hyperledger/fabric-couchdb:latest   "tini -- /docker-ent…"    About a minute ago   Up 59 seconds             4369/tcp, 9100/tcp, 0.0.0.0:7008->5984/tcp       peer1.org1.example.com.couchdb
fa07e5c8c32c   hyperledger/fabric-couchdb:latest   "tini -- /docker-ent…"    About a minute ago   Up About a minute         4369/tcp, 9100/tcp, 0.0.0.0:7007->5984/tcp       peer2.org0.example.com.couchdb
31bf9d0dc3d3   hyperledger/fabric-couchdb:latest   "tini -- /docker-ent…"    About a minute ago   Up About a minute         4369/tcp, 9100/tcp, 0.0.0.0:7006->5984/tcp       peer1.org0.example.com.couchdb`

**Comment by litong01** [comment]
@ivanv6 if you use the flag to indicate using couchdb and -e to expose ports, then couchdb admin port will be exposed and the default admin user id and pw will be admin/adminpw,  I think. Give it a try. if everything works, do not forget to close this.

**Comment by ivanv6** [comment]
@litong01 thanks a lot, it works. I had another problem, on the Couchdb i cant see the value of 'a' and 'b' parameters for the simple chaincode. In attachment you can see the couchdb interface. How can I handle it? 

![image](https://user-images.githubusercontent.com/25437300/114620934-63f15380-9cac-11eb-9efa-8051c7ac93ff.png)

**Comment by litong01** [comment]
I have no idea. You probably can look into how couchdb saves tx data. This is not something minifabric did. Please close this issue.

**Comment by ivanv6** [comment]
Yes you are right. Thanks a lot!
