### ISSUE TITLE
HLEP

### ISSUE THREAD

**Issue by zwnode** [hyperledger-labs/minifabric#186]
hello,can I test the consensus algorithm with minifabric?

**Comment by litong01** [comment]
What consensus algorithm ?

**Comment by zwnode** [comment]
> What consensus algorithm ?
Like PBFT, I want to test it's TPS

**Comment by litong01** [comment]
minifabric only setup Fabric network use raft.

**Comment by zwnode** [comment]
> minifabric only setup Fabric network use raft.

I'm currently researching consensus algorithms and I don't know how to test the performance of consensus algorithms. Can you give me some suggestions or recommend me some tutorials?

**Comment by litong01** [comment]
if you have questions please go to the rocket fabric channel to ask your questions. This is to open issues against minifabric. What you are asking here is not really an issue.
