### ISSUE TITLE
Help:

### ISSUE THREAD

**Issue by zwnode** [hyperledger-labs/minifabric#188]
![image](https://user-images.githubusercontent.com/75482436/114805566-cf831000-9dd5-11eb-8183-057123d2901e.png)

I run minifab up, and  it meets problem ,just like the picture shows,how to deal with this problem?

**Comment by litong01** [comment]
@zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.

**Comment by zwnode** [comment]
> @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.



> @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.

OK，i run the command minifab up, it  meets error with the step of cc install,

**Comment by zwnode** [comment]
> > @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.
> 
> > @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.
> 
> OK，i run the command minifab up, it meets error with the step of cc install,

my env is  Linux Ubuntu20.04.1

**Comment by zwnode** [comment]
> > > @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.
> > 
> > 
> > > @zwnode you got give a bit more on your env, os, command that you run so that anyone can help you out.
> > 
> > 
> > OK，i run the command minifab up, it meets error with the step of cc install,
> 
> my env is Linux Ubuntu20.04.1

i think the error is about go proxy, but i can  access to google site, so what i should do to solve this problem?

**Comment by zwnode** [comment]
i run this command go env -w GOPROXY=https://goproxy.cn to change go proxy ,but it still doesn't work.

**Comment by litong01** [comment]
@zwnode look at this file,https://github.com/hyperledger-labs/minifabric/blob/main/spec.yaml, pay attention to the line 22, to line 25 specifically for this kind of issue. I think you need to make a copy of this file and place it in your current directory, then the settings in the spec.yaml file will allow you to use different proxy, then you should be fine.

**Comment by zwnode** [comment]
> @zwnode look at this file,https://github.com/hyperledger-labs/minifabric/blob/main/spec.yaml, pay attention to the line 22, to line 25 specifically for this kind of issue. I think you need to make a copy of this file and place it in your current directory, then the settings in the spec.yaml file will allow you to use different proxy, then you should be fine.

it still doesn't work ,the file is already in the directory when i colne minifab, and i run the command go env ,the proxy is https://goproxy.io,direct ,    Is there anything else I need to modify? 
![image](https://user-images.githubusercontent.com/75482436/115098627-9f697780-9f63-11eb-8c44-4a99adaa8358.png)

**Comment by zwnode** [comment]
> > @zwnode look at this file,https://github.com/hyperledger-labs/minifabric/blob/main/spec.yaml, pay attention to the line 22, to line 25 specifically for this kind of issue. I think you need to make a copy of this file and place it in your current directory, then the settings in the spec.yaml file will allow you to use different proxy, then you should be fine.
> 
> it still doesn't work ,the file is already in the directory when i colne minifab, and i run the command go env ,the proxy is https://goproxy.io,direct , Is there anything else I need to modify?
> ![image](https://user-images.githubusercontent.com/75482436/115098627-9f697780-9f63-11eb-8c44-4a99adaa8358.png)
![image](https://user-images.githubusercontent.com/75482436/115098819-c3798880-9f64-11eb-98a9-608752eed4a2.png)

**Comment by litong01** [comment]
@zwnode as I said you need to pay attention to the lines that I said above. you are not using the right proxy. Try to use this one `goproxy.cn`, not `goproxy.io`

**Comment by litong01** [comment]
whatever go env you set up in your own shell does not matter, minifabric does not use any of these. Please change settings  in spec.yaml file. That is the only place that you can change settings. Please also read docs in the docs directory, it will be a great help for you.

**Comment by zwnode** [comment]
> whatever go env you set up in your own shell does not matter, minifabric does not use any of these. Please change settings in spec.yaml file. That is the only place that you can change settings. Please also read docs in the docs directory, it will be a great help for you.

can you tell me how to change settings, i trid but failed, i'm a new hand.

**Comment by zwnode** [comment]
> > whatever go env you set up in your own shell does not matter, minifabric does not use any of these. Please change settings in spec.yaml file. That is the only place that you can change settings. Please also read docs in the docs directory, it will be a great help for you.
> 
> can you tell me how to change settings, i trid but failed, i'm a new hand.
![image](https://user-images.githubusercontent.com/75482436/115178248-7849ac00-a103-11eb-9668-e9a1eeb3cf9c.png)

Is there any problems?

**Comment by litong01** [comment]
@zwnode try place the following content in spec.yaml file and place the file in your working directory, then make sure your env is clean. then try `minifab up`

```
fabric:
  cas:
  - "ca1.org0.example.com"
  - "ca1.org1.example.com"
  peers: 
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  - "peer1.org1.example.com"
  - "peer2.org1.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  goproxy: "https://goproxy.cn,direct"
```

**Comment by zwnode** [comment]
> @zwnode try place the following content in spec.yaml file and place the file in your working directory, then make sure your env is clean. then try `minifab up`
> 
> ```
> fabric:
>   cas:
>   - "ca1.org0.example.com"
>   - "ca1.org1.example.com"
>   peers: 
>   - "peer1.org0.example.com"
>   - "peer2.org0.example.com"
>   - "peer1.org1.example.com"
>   - "peer2.org1.example.com"
>   orderers:
>   - "orderer1.example.com"
>   - "orderer2.example.com"
>   - "orderer3.example.com"
>   goproxy: "https://goproxy.cn,direct


I do as you said ,it run sucessgul Thank you very much ,it mean a lot to me  

> @zwnode try place the following content in spec.yaml file and place the file in your working directory, then make sure your env is clean. then try `minifab up`
> 
> ```
> fabric:
>   cas:
>   - "ca1.org0.example.com"
>   - "ca1.org1.example.com"
>   peers: 
>   - "peer1.org0.example.com"
>   - "peer2.org0.example.com"
>   - "peer1.org1.example.com"
>   - "peer2.org1.example.com"
>   orderers:
>   - "orderer1.example.com"
>   - "orderer2.example.com"
>   - "orderer3.example.com"
>   goproxy: "https://goproxy.cn,direct"
> ```

i do as you said and it run successfully. Thank you for your help,it mean a lot to me .
