### ISSUE TITLE
Support M1 mac with docker image

### ISSUE THREAD

**Issue by MrGru** [hyperledger-labs/minifabric#200]
Failed when run `./minifab up` on M1 mac.

![image](https://user-images.githubusercontent.com/3302193/117095853-b5fc3500-ad91-11eb-8451-0bf21a096dfe.png)

**Comment by litong01** [comment]
current we do not support M1 chipped mac os. It got a lot of issues which not related to how minifabric is done.

**Comment by litong01** [comment]
minifabric does not support M1 chip at present. Closing this for now.
