### ISSUE TITLE
TLS handshake error between CA container on k8s and client using generated profile (by minifab profilegen)

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#205]
as the result,  FabricCAClient::enroll  (Fabric SDK API) failed, in case of k8s environment.
CA container log says:
```
:
2021/05/12 08:00:32 [DEBUG] Attempting fallback with certfile /etc/hyperledger/fabric-ca/tlscerts/tls.crt and keyfile /etc/hyperledger/fabric-ca/tlscerts/tls.key
2021/05/12 08:00:32 [DEBUG] Client authentication type requested: noclientcert
2021/05/12 08:00:32 [INFO] Listening on https://0.0.0.0:7054
2021/05/12 08:09:27 http: TLS handshake error from 10.244.0.9:45306: remote error: tls: unknown certificate
```
This error doesn't happen on docker environment.

**Comment by itaru2622** [comment]
when I tested with small patch,  FabricCAClient::enroll (Fabric SDK API) succeeded.
the patch is targeted to playbooks/ops/netup/k8stemplates/allnodes.j2
```patch
         - { name: "FABRIC_CA_SERVER_CA_KEYFILE", value: "/etc/hyperledger/fabric-ca/idcerts/tls.key" }
         - { name: "FABRIC_CA_SERVER_CA_CERTFILE", value: "/etc/hyperledger/fabric-ca/idcerts/tls.crt" }
         - { name: "FABRIC_CA_SERVER_TLS_ENABLED", value: "true" }
-        - { name: "FABRIC_CA_SERVER_TLS_KEYFILE", value: "/etc/hyperledger/fabric-ca/tlscerts/tls.key" }
-        - { name: "FABRIC_CA_SERVER_TLS_CERTFILE", value: "/etc/hyperledger/fabric-ca/tlscerts/tls.crt" }
+        - { name: "FABRIC_CA_SERVER_TLS_KEYFILE", value: "/etc/hyperledger/fabric-ca/idcerts/tls.key" }
+        - { name: "FABRIC_CA_SERVER_TLS_CERTFILE", value: "/etc/hyperledger/fabric-ca/idcerts/tls.crt" }
```
the above patch means the FABRIC_CA_SERVER_TLS_CERTFILE and FABRIC_CA_SERVER_CA_CERTFILE are the same.
The above patch derived from docker environment case ( playbooks/ops/netup/templates/caenv.j2 ).
In docker case,  both value is the same as bellow:

```
# playbooks/ops/netup/templates/caenv.j2
FABRIC_CA_SERVER_CA_KEYFILE=/certs/ca/{{ allkeys[item.org].pkey.split('/')[-1] }}
FABRIC_CA_SERVER_CA_CERTFILE=/certs/ca/{{ item.fullname }}-cert.pem
FABRIC_CA_SERVER_TLS_KEYFILE=/certs/ca/{{ allkeys[item.org].pkey.split('/')[-1] }}
FABRIC_CA_SERVER_TLS_CERTFILE=/certs/ca/{{ item.fullname }}-cert.pem
# CA container environment
FABRIC_CA_SERVER_CA_KEYFILE=/certs/ca/priv_sk
FABRIC_CA_SERVER_CA_CERTFILE=/certs/ca/ca1.org0.example.com-cert.pem
FABRIC_CA_SERVER_TLS_KEYFILE=/certs/ca/priv_sk
FABRIC_CA_SERVER_TLS_CERTFILE=/certs/ca/ca1.org0.example.com-cert.pem
```

**Comment by itaru2622** [comment]
for PR, there are two choices, at least:

choice A) the above patch (minimal modification)
choice B) the above patch with removing garbage (the following line etc).
``` patch
      volumes:
      - name: cert-key-id
        secret:
          secretName: "{{ nodename }}-secret"
-     - name: cert-key-tls
-       secret:
-          secretName: "{{ nodename }}-tls-secret"
:
      volumeMounts:
       - { mountPath: "/etc/hyperledger/fabric-ca/idcerts", name: "cert-key-id" }
-      - { mountPath: "/etc/hyperledger/fabric-ca/tlscerts", name: "cert-key-tls" }
```
I'm not sure which choice is preferable for minifabric maintainers. any suggestion?

**Comment by litong01** [comment]
@itaru2622 certs are saved as secret in k8s env. it will have to be coming from k8s secret, then mounted onto the pod. not really sure what you mean about garbage. Please elaborate.

**Comment by itaru2622** [comment]
@litong01 my minimal patch means that 
CA pod uses /etc/hyperledger/fabric-ca/idcerts but not /etc/hyperledger/fabric-ca/tlscerts.

in case of choice A, 
/etc/hyperledger/fabric-ca/tlscerts will be mount in CA pod via cert-key-tls secret even it is not used. then, garbage remained.

in case of choice B,  /etc/hyperledger/fabric-ca/tlscerts and cert-key-tls secret will be removed from the pod.

**Comment by litong01** [comment]
@itaru2622 ok. If something is not used, then please remove the mounting. Thanks.

**Comment by itaru2622** [comment]
@litong01 ok, I will take choice B for the PR.
