### ISSUE TITLE
[bug] minifab cleanup doesn't remove entries from ingress on k8s

### ISSUE THREAD

**Issue by itaru2622** [hyperledger-labs/minifabric#221]
This issue occurs  just in case of k8s but not docker environment.

There is no task to care about vars/run/allservices.yaml in playbook/ops/netdown.
as the result, entries in ingress controller become garbage...

```bash
# after minifab cleanup
kubectl get svc -A
NAMESPACE       NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP                                                                    PORT(S)                                                                                                                                                             AGE
: 
ingress-nginx   ingress-nginx-controller             LoadBalancer   10.100.23.143   IPaddr 7000:32377/TCP,7001:31823/TCP,7006:30410/TCP,7007:32672/TCP,7008:30675/TCP,7002:30342/TCP,7003:31414/TCP,7004:30366/TCP,7005:30572/TCP,80:31044/TCP,443:30533/TCP

# the above should be just two entries as bellow:
ingress-nginx   ingress-nginx-controller             LoadBalancer   10.100.23.143   IPaddr 80:31044/TCP,443:30533/TCP

```

```bash
#  for netdown :
find playbooks/ops/netdown -type f | xargs grep -n allservices | wc -l
0

# for netup :
find playbooks/ops/netup -type f | xargs grep -n allservices
playbooks/ops/netup/k8sapply.yaml:31:    src: "{{ pjroot }}/playbooks/ops/netup/k8stemplates/allservices.j2"
playbooks/ops/netup/k8sapply.yaml:32:    dest: "{{ pjroot }}/vars/run/allservices.yaml"
playbooks/ops/netup/k8sapply.yaml:38:    src: "{{ pjroot }}/vars/run/allservices.yaml"
```

**Comment by litong01** [comment]
I think this is an issue and a fix PR would be nice.

**Comment by itaru2622** [comment]
hmm, I'm working this issue, and I got some trouble in ansible k8s module...

my basic idea is using 'kubectl  patch' feature  with --type json -p={op:remove ... }
and kubectl command works fine, but ansible k8s's "merge_type:json"  doesn't work.

when I checked github and stackoverflow ,  it seems to be buggy, and under rebuilding as k8s_json_patch.

I'm not sure what is best choice yet,
but if  ingress-controller was installed within minifab namespace(NETNAME) beside default ingress-nginx namespace,
minifab can handle more easier.

**Comment by litong01** [comment]
@itaru2622 nginx was not installed into minifab namespace was on purpose. When you have multiple namespaces for different orgs, you probably do not want to have nginx ingress controller in each namespace considering resource costs. Now for the issue on hands, I think allservices.j2 basically setup the configmap and updated the nginx controller and its service, the reverse will need to be done when doing cleaning up. If the k8s task is having trouble dealing with patch merge, then I am not really sure what else we can do.

**Comment by itaru2622** [comment]
@litong01 yes, I undeerstood about
- processing reverse order in netdown.
- avoid installing ingress each minifab namespace to reduce resources.

This issue is tough to fix because of ansible k8s merge_type:json trouble.

When I tested with openshift v0.11, removing task says succeesed but actually, entries are still remained.
When I tested kubernetes.core.k8s_json_patch (requires openshift v0.12), it raised error which described https://github.com/kubernetes-client/python/issues/1333

**Comment by itaru2622** [comment]
I finally could remove entries from ingress's configmap by:
```yaml
kubernetes.core.k8s_json_patch:
    kubeconfig: "{{ pjroot }}/vars/kubeconfig/config"
    kind: ConfigMap
    namespace: ingress-nginx
    name: tcp-services
    patch:
      - op: remove
        path: "/data/{{item}}"
  with_items: ...
```
where  kubernetes.core.k8s_json_patch involved by
```ansible-galaxy collection install git+https://github.com/ansible-collections/kubernetes.core.git ```

unfortunately, the above cannot be used with openshift's kubernetes module by unknown reason.

then, all 'k8s:' and 'k8s_info:' needs to be rewritten by kubernetes.core.k8s and other corresponding keywords.
It is big impact...

**Comment by itaru2622** [comment]
@litong01 do you have any idea or suggestion for this issue?

choice1) change all k8s related tasks from openshift's  k8s to kubernetes.core.k8s, for support removing ingress entry. 
choice2) for a while, watch openshift activity then deside next action. in this case it is better to post a issue report.

**Comment by litong01** [comment]
@itaru2622 I do not mind at all using kubernetes.core.k8s tasks instead of openshift k8s_info. There will be some changes necessary, but I do not think it will be overwhelming since these tasks basically only used in couple of files. Can you see which package is most active and actively maintained? Thanks for trying to improving Minifabric.

**Comment by itaru2622** [comment]
@litong01 I agree that servaying packages should be done before changing implementation. 

unfortunately, it may be tough work because of  number of choices(packages), and requirement feature (supporting patch remove operation), beside I'm not well familiar to kubernetes nor ansible world yet.

**Comment by litong01** [comment]
@itaru2622 ok. Probably just looking into these two packages and see how the communities are doing in general such as contributions and most recent commits etc.

**Comment by itaru2622** [comment]
The following page says as Caveats:

community.kubernetes(k8s module) is going to migrate kubernetes.core
 
https://docs.ansible.com/ansible/latest/scenario_guides/kubernetes_scenarios/scenario_k8s_object.html

but not sure the target day of migration completed (roadmap schedule etc.)

anyway, according to following page, both are entried in top three in downlads.

https://galaxy.ansible.com/search?deprecated=false&keywords=kubernetes&order_by=-download_count&page=1

there is a post describing and discussing migration  task:
 
https://github.com/ansible-collections/kubernetes.core/issues/ number 32

those are good news to take kubernetes.core.
it may need investigation in development aspect.

**Comment by itaru2622** [comment]
@litong01 unfortunately, I found that we cannot migrate to kubernetes.core at this moment.

as the result, we cannot remove entries from ingress configmap in default ingress-nginx namespace.

what I observed:
- kubernetes.core gets stucked while sending genesis.block to k8s.
- community.kubernetes.k8s also gets stucked because it just redirects to kubernetes.core in deep layer.
- it succeeded in conversion by {{ genesis.block | b64encode }}, so it has trouble in operation with k8s.

**Comment by itaru2622** [comment]
I reported  issue as https://github.com/ansible-collections/kubernetes.core/issues/140

**Comment by itaru2622** [comment]
latest kubernetes.core and its dependency is now ready to use since kubernetes.core issur 140 is fixing.

actually, I already succeeded to setup HLF with minifabric + kubernetes.core, and also succeeded to remove tcp-services entry from ingress  configmap by my local testing playbook.

but before leasing it, there is still other issue to solve in minifabric ... it raised by bumpup versions.
I will post that issue separatly.
