### ISSUE TITLE
How to use REST API to invoke chaincode methods

### ISSUE THREAD

**Issue by alphacybercom** [hyperledger-labs/minifabric#232]
I've installed a custom chaincode and I'd need to invoke a custom method of such chaincode through REST API.

I saw that it is possible to access the REST API definition (Swagger UI) on [http://localhost:8080/api-docs/](http://localhost:8080/api-docs/), but I've not found information on how to trigger custom methods of my chaincode, feature useful to me, in order to provide an extry point to connect external software to the blockchain.

Hence, how can I invoke custom methods of my chaincode through REST APIs?

**Comment by itaru2622** [comment]
This is not  minifabric issue but application matter, I think.
Hyperledger provides Fabric SDKs for languages, and they can be used with the REST framework.

You may get better answer if choosing appropriate place to ask.
some FAQ exists, such as: https://stackoverflow.com/questions/59347073/hyperledger-rest-server-or-sdk

please close this issue.

**Comment by alphacybercom** [comment]
Solved by implementing a separate app, based on what reported in [https://jira.hyperledger.org/browse/FABN-1559](https://jira.hyperledger.org/browse/FABN-1559) (see [sample app](https://jira.hyperledger.org/secure/attachment/18333/App.js)), where pointers to files are described in [https://github.com/Anil8753/TRUWare/blob/main/testapp/go/ledger.go](https://github.com/Anil8753/TRUWare/blob/main/testapp/go/ledger.go).
