### ISSUE TITLE
Failed to create ca self signed certificate

### ISSUE THREAD

**Issue by yilin-sai** [hyperledger-labs/minifabric#233]
When I run minifab with a k8s config file, `minifab up -e true` failed at the "Create ca self signed certificate" step with the following message:
```
......
# Create ca self signed certificate ***************************
  One or more items failed
    non-zero return code
    non-zero return code

# STATS *******************************************************
minifab: ok=64	failed=1
```

I've updated minifab to the latest version, but the error persists. Does anyone know what could be the reason or how should I debug this? Thank you!

**Comment by litong01** [comment]
Sounds like you may not have k8s setup right. Make sure your k8s is running ok and your kubconfig file is in the right place.

**Comment by yilin-sai** [comment]
Hi @litong01 , thank you for your reply!

I created an EKS token and made it available to minifab using the following scripts:
```
CONTEXT=$(kubectl config current-context)
TOKEN=$(aws eks get-token --cluster-name "HLF" | jq -r '.status.token')
kubectl config set-credentials $CONTEXT --token=$TOKEN

(in minifab working directory)
mkdir -p ./vars/kubeconfig
cp ~/.kube/config ./vars/kubeconfig/config
```
After that, I also confirmed the k8s config file was working by running `kubectl get nodes`.

My spec.yaml looks like this:
```
fabric:
    cas:
        ...
    peers:
        ...
    orderers:
        ...
    settings:
        ...
    ### set the endpoint address to override the automatically detected IP address
    endpoint_address: ${HLF_ENDPOINT}
    ### set the docker network name to override the automatically generated name.
    netname: 'hlf'
```

I think I followed all the instructions correctly, but still got the same error.

A weird thing is after I got the above error, if I ran `minifab up -e true` again, this time it would fail at a later step "Deploy all nodes and their service" with a "namespace not found" error:
```
Deploy all nodes and their service **************************
  Service ca1-orchestrator: Failed to create object: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \\"hlf\\" not found","reason":"NotFound","details":{"name":"hlf","kind":"namespaces"},"code":404}\n'
```
It seems that somehow the "create namespace" step at https://github.com/hyperledger-labs/minifabric/blob/fec704b2d0ae53177f313efc8755f03ea799bfa6/playbooks/ops/certgen/orgkeygen.yaml#L56 has been skipped.

Did I misconfigured anything in spec.yml? Much appreciated for your help!

**Comment by yilin-sai** [comment]
Hi @litong01 , I found the cause of the error, it's because I used the url instead of IP address as the `endpoint_address` in `spec.yaml`.

But now `minifab up -e true` failed when creating channel:
```
# Running operation: ******************************************
  channel create
.....
# Run the channel creation script on cli container ************
  non-zero return code
  2021-07-13 21:30:21.400 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2021-07-13 21:30:21.416 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2021-07-13 21:30:21.417 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2021-07-13 21:30:21.980 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  Error: failed to create deliver client for orderer: orderer client failed to connect to <IP_ADDRESS>:7006: failed to create new connection: context deadline exceeded

# STATS *******************************************************
minifab: ok=254	failed=1
```
And `minifab stats` shows the network status is 0%. I installed ingress controller using
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.44.0/deploy/static/provider/cloud/deploy.yaml
```
According to https://kubernetes.github.io/ingress-nginx/deploy/#aws, I've also tried:
```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.47.0/deploy/static/provider/aws/deploy.yaml
```

Do you know what could be wrong?

**Comment by litong01** [comment]
Did you have Nginx ingress controller installed? It requires that to create endpoints for various nodes. If you do not have Nginx ingress installed correctly, things won't work. I suggest that you make sure that your Nginx ingress controller works as expect and use the public IP address in the spec file. To make sure things will go well, remove everything in your k8s cluster and start fresh.

**Comment by yilin-sai** [comment]
Pretty sure the Nginx ingress controller is installed and running.

I got the IP address by using the CLUSTER-IP field in
```
> kubectl get svc --namespace=ingress-nginx
NAME                                 TYPE           CLUSTER-IP      EXTERNAL-IP                                                                   PORT(S)                      AGE
ingress-nginx-controller             LoadBalancer   10.100.144.39   a9e285d2ccbca449e883d7daec055c65-228184942.ap-southeast-2.elb.amazonaws.com   80:32713/TCP,443:30347/TCP   42m
```

is this the correct way to get the IP address?

**Comment by yilin-sai** [comment]
Turns out I've been using the wrong IP address. `ping` the EXTERNAL-IP field gives the correct IP address. Now things work great! Thank you @litong01 !
