### ISSUE TITLE
Spin up a network with 2 channels

### ISSUE THREAD

**Issue by yilin-sai** [hyperledger-labs/minifabric#236]
Hi! Thank you for this great tool! I'm wondering what is the easiest way to spin up a minifab network with 2 channels. For example, org A and org B in channel 1, and org A and org C in channel 2.

From the documentation, the `join` command always applies to all peers in the network, so the only way I can think of is to first spin up 3 one-org networks, with org A, B, and C respectively  (using 3 spec.yaml), then connect network A with network B, finally connect network A with network C (using `minifab nodeimport`).

The above seems a bit of a hassle, considering I just want to set up two channels. Is there a better way to achieve it?

Thanks!

**Comment by litong01** [comment]
@yilin-sai minifabric as a product was meant to produce something quick and easy for developers. It can certainly be used to do what you described. Thinking about a production like env, you would normally create a new org and going through steps of adding the new org and its node to an existing network, that should be the most common use cases, what you described is almost identical to the common case, I do not think it is a hassle. If there is a short cut, then most likely you would be basically combining these steps into a script or some sort, it would not change the fact that you have to do things like that. Please close this issue.

**Comment by yilin-sai** [comment]
I see. Thank you!
