### ISSUE TITLE
Explorer support for Kubernetes

### ISSUE THREAD

**Issue by ntheile** [hyperledger-labs/minifabric#245]
I deployed to kubernetes but when i run `minifab explorerup -e true` it does not deploy to my kubernetes environment.

**Comment by litong01** [comment]
It is not supported at this point for k8s. You are very welcome to contribute to minifabric to make this feature available for k8s

**Comment by ntheile** [comment]
i found this guide on deploying explorer to kubernetes https://github.com/feitnomore/hyperledger-fabric-kubernetes#step-17-deploy-hyperledger-explorer . I might give it a try.

**Comment by litong01** [comment]
@ntheile it will be great to have you contributing to Minifabric. looking forward to your PR. Thanks.
