### ISSUE TITLE
Unable to get the minifab.cmd file

### ISSUE THREAD

**Issue by boyappstudio** [hyperledger-labs/minifabric#246]
Hi there,

I'm very new to Hyperledger Fabric and not sure what steps I've missed. 

I've run the below command on my Windows 10 and tried to start minifab with no success.

mkdir %userprofile%\mywork & cd %userprofile%\mywork & curl -o minifab.cmd -sL https://tinyurl.com/y3gupzby

Then, I tried to recheck minifab.cmd by going to https://tinyurl.com/y3gupzby and it said 404: Not Found.

It seems the file is missing? Can you please help fix this issue?

Thanks a lot for your help.

**Comment by boyappstudio** [comment]
Sorry I've found the way to start using minifab. I will close this issue now. Thank you.

**Comment by ntheile** [comment]
it appears the file name changed and added the .bat extension https://raw.githubusercontent.com/hyperledger-labs/minifabric/master/minifabwin.bat 

@litong01 i think the tinyurl need to be updated to reflect the new .bat extension

**Comment by litong01** [comment]
@ntheile I think @itaru2622 recently changed the file which may have broken this. Please open an issue and ask in the issue to change it back. We want these things to work. Thanks Nick.
