### ISSUE TITLE
Incorrent tinyurl link

### ISSUE THREAD

**Issue by mvkillu** [hyperledger-labs/minifabric#257]
In the README.md and docs/README.md, the tinyurl link to fetch the minifabwin.bat script seems to be incorrect as it is pointing to a 404 on Github.

```
mkdir %userprofile%\mywork & cd %userprofile%\mywork & curl -o minifab.cmd -sL https://tinyurl.com/y3gupzby
```

I guess the tinyurl link should point to https://raw.githubusercontent.com/hyperledger-labs/minifabric/master/minifabwin.bat

**Comment by litong01** [comment]
@mvkillu please see this PR. https://github.com/hyperledger-labs/minifabric/pull/258 it should fix the issue

**Comment by litong01** [comment]
This has been fixed, please @mvkillu verify and close. Thanks.

**Comment by mvkillu** [comment]
Perfect. Thank you.
