### ISSUE TITLE
Add an app sample to provide REST API to interact with the chaincode

### ISSUE THREAD

**Issue by alphacybercom** [hyperledger-labs/minifabric#269]
I propose to add a sample app (in the `/app/` directory) implementing a REST server providing APIs to interact with a specific chaincode.
As far as I understand, this is the right approach to implement REST APIs allowing external programs to interact with the blockchain.

**Comment by Anil8753** [comment]
I believe this is out of scope for this minifabric as REST API server is an individual choice (Go, Node, Java, within programming languages variety of web frameworks)
Implementing API server is fairly easy, you need only 2 things `connection profile` and `Wallet`. You can refer to [https://github.com/Anil8753/TRUWare/tree/main/testapp/go](https://github.com/Anil8753/TRUWare/tree/main/testapp/go)
It exposes the default deployed chaincode web interface

**Comment by alphacybercom** [comment]
Thank you @Anil8753 for your reply.
Neverthless, the mentioned samples seems not to interact with the chaincode methods. Please let me know if I am wrong.
Also, the last link does not work.

**Comment by Anil8753** [comment]
@alphacybercom update the link
**To get the contract**
https://github.com/Anil8753/TRUWare/tree/main/app/warehouse/api/connector

**Calling the chaincode functions**
https://github.com/Anil8753/TRUWare/blob/main/testapp/go/ledger.go

chaincode function: 'query"
`contract.EvaluateTransaction("query", party)`

chaincode function: 'invoke" with parameters party1 = 'a' , party2 = 'b' , amount = '10'
`contract.SubmitTransaction("invoke", party1, party2, strconv.Itoa(amount))`

**Comment by alphacybercom** [comment]
Thank you, in my case, as I prefer using node, I started using [this sample](https://jira.hyperledger.org/secure/attachment/18333/App.js) (also see the [main link](https://jira.hyperledger.org/browse/FABN-1559)), applying the file pointers reported [in your link](https://github.com/Anil8753/TRUWare/blob/main/testapp/go/ledger.go).
