### ISSUE TITLE
Running out of space quickly

### ISSUE THREAD

**Issue by alphacybercom** [hyperledger-labs/minifabric#281]
I've deployed a simple chaincode with `minifab`.
By monitoring at the disk usage, I see that, even when no operations are accomplished, hence, by leaving the "blockchain alone", up and running, the available disk space quickly goes to `0`.

In particular, through monitoring, I got that (on the conditions reported above, hence, only the blockchain in running, with no operations), `13MB` per minute are seized (mainly, on the `/var/lib/docker/containers` directory).
This is a huge amount of data, by considering that no operation is accomplished on the blockchain.

Of course, I believe this depends on some sort of logging capability, that should be suppressed in some way.

How to solve the issue?

**Comment by litong01** [comment]
Logging level probably is debug. You can set that to error to avoid docker logs filling up your space.

**Comment by alphacybercom** [comment]
Thank you. How to do that?

**Comment by alphacybercom** [comment]
Tried to look at `minifab -h`, but nothing useful appears. Should it be specified in the `spec.yaml` file?

**Comment by litong01** [comment]
That is right, use FABRIC_LOGGING_SPEC: ERROR.

**Comment by alphacybercom** [comment]
Thanks, it appears to be working as expected now.
