### ISSUE TITLE
New Channel - Same Network - Less Orgs

### ISSUE THREAD

**Issue by rafa977** [hyperledger-labs/minifabric#288]
Hello to all,

I am facing an issue which is while I create a new channel in my current working network. I have constructed my network using a spec.yaml file that has 3 orgs inside. After I created the network I wanted to create a new channel where only the two of the three orgs need to join the channel and communicate.
I tried this by removing from my spec.yaml file the org that I don't want to be included and run the join command. 
But I still get all orgs join in the channel.

Any ideas? Thank you

**Comment by litong01** [comment]
This is not how things were designed to work. If you want to do what you described, you want to setup two org site and one org site. This way, one channel can only have two orgs in.
