### ISSUE TITLE
ARM support for minifabric

### ISSUE THREAD

**Issue by KSilkThread** [hyperledger-labs/minifabric#293]
Related to: #278

 Hi Folks,

@CodingSinceThe80s and me started to work on ARM support for minifabric. 
For testing purpose we built minifabric locally and replaced all the references of hyperledger/fabric-XXX images by our armhf (fabric v 2.2) images (see https://hub.docker.com/r/razvanhr/armfabricimages/tags). Our setup runs on a RPI 4 with 4GB RAM and Raspbian (armhf), using Docker version 20.10.9, build c2ea9bc. The containers from the default spec.yaml setup are starting successful, but we encountered the following problem.

Starting a new network with: `minifab up -i 2.2 -e true`

We only modified the endpoint_address of the default spec.yaml for each case. 

### 1. without setting the endpoint in spec.yaml (picks automatically eth0)
```
# Fabric network peer and orderer node health status **********
  peer1.org0.example.com 
  peer2.org0.example.com 
  peer1.org1.example.com 
  peer2.org1.example.com 
  orderer1.example.com 
  orderer2.example.com 
  orderer3.example.com "OK"
  Network Status: 14%

# Running operation: ******************************************
  channel create
.....
# Run the channel creation script on cli container ************
  non-zero return code
  2021-10-16 11:39:04.704 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2021-10-16 11:39:04.845 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2021-10-16 11:39:04.846 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2021-10-16 11:39:04.862 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  Error: failed to create deliver client for orderer: orderer client failed to connect to 192.168.8.104:7007: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 192.168.8.104:7007: connect: connection refused"

# STATS *******************************************************
minifab: ok=250	failed=1	
```

### 2. setting the the endpoint to 0.0.0.0 in spec.yaml
```
# Fabric network peer and orderer node health status **********
  peer1.org0.example.com "OK"
  peer2.org0.example.com "OK"
  peer1.org1.example.com "OK"
  peer2.org1.example.com "OK"
  orderer1.example.com "OK"
  orderer2.example.com "OK"
  orderer3.example.com "OK"
  Network Status: 100%

# Running operation: ******************************************
  channel create
.....
# Run the channel creation script on cli container ************
  non-zero return code
  2021-10-16 12:04:33.596 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2021-10-16 12:04:33.730 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2021-10-16 12:04:33.730 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2021-10-16 12:04:33.745 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  Error: failed to create deliver client for orderer: orderer client failed to connect to 0.0.0.0:7007: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 0.0.0.0:7007: connect: connection refused"

# STATS *******************************************************
minifab: ok=250	failed=1	
```
### 3. setting the endpoint to 127.0.0.1 in spec.yaml
```
# Fabric network peer and orderer node health status **********
  peer1.org0.example.com "OK"
  peer2.org0.example.com "OK"
  peer1.org1.example.com "OK"
  peer2.org1.example.com "OK"
  orderer1.example.com "OK"
  orderer2.example.com "OK"
  orderer3.example.com "OK"
  Network Status: 100%

# Running operation: ******************************************
  channel create
.....
# Run the channel creation script on cli container ************
  non-zero return code
  2021-10-16 12:24:57.755 UTC [common.tools.configtxgen] main -> INFO 001 Loading configuration
  2021-10-16 12:24:57.895 UTC [common.tools.configtxgen.localconfig] Load -> INFO 002 Loaded configuration: /vars/configtx.yaml
  2021-10-16 12:24:57.895 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 003 Generating new channel configtx
  2021-10-16 12:24:57.910 UTC [common.tools.configtxgen] doOutputChannelCreateTx -> INFO 004 Writing new channel tx
  Error: failed to create deliver client for orderer: orderer client failed to connect to 127.0.0.1:7007: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7007: connect: connection refused"

# STATS *******************************************************
minifab: ok=250	failed=1	
```

For all three cases the firewall was inactive (ufw disable), no port rules were set. It still looks like some port settings are incorrect and therefore refused connection. - Any suggestion?

Are there more things to consider? We try to collect further requirements for the integration checklist.
If the setup fully succeeds, our goal would be to implement a new command for importing a set of custom ARM images automatically.

**Comment by litong01** [comment]
@KSilkThread it seems to me that the issue is really about networking which should be independent from platforms. I wonder if your env has these ports open, I know some of the linux has ports blocked by default. Try to stand up a nginx docker on one of the ports and see if you can hit the port.

**Comment by litong01** [comment]
Really like your guys effort to make it working on ARM. much appreciated.

**Comment by CodingSinceThe80s** [comment]
@litong01 Thanks for the tip, I believe the issue is linked to dns-resolution in the docker engine itself. The weird part here: One of the 3 orderers (not the same one each time) is being started, the other 2 fail saying the cannot resolve the hostnames of the others. If we log into one of the containers via interactive shell and ping that orderer by dns-name it is being resolved. Really curious behavior...

**Comment by KSilkThread** [comment]
short update - instead of raspbian and armhf, now I was testing this setup on ubuntu with arm64, using the images from https://github.com/chinyati/Hyperledger-Fabric-ARM64-images - which lead to the same "connection refused"-behavior.

**Comment by litong01** [comment]
@KSilkThread minifabric create a docker network, then all the ports will be on that docker network. Not really sure if your env allows that. The test you did was probably using the docker host network. Please try the same thing but using the docker network that minifabric created by --network parameter to your command when you stand up nginx container. This test is to ensure that your env or os is not blocking access to the ports that minifabric is trying to setup fabric nodes on.

**Comment by KSilkThread** [comment]
Thanks @litong01 for the hint, did not realized that. I performed the test again with:
`docker run --name mynginx1 --network mysite -p 7006:80 -d nginx`
 
In portainer my setup look like this: 
![image](https://user-images.githubusercontent.com/12004185/139725671-3575f7f2-9a44-4adf-bc5b-d7f721c07821.png)

After this I was able to reach nginx default page in firefox localhost:7006, also opening the logs in portainer I can see the request by firefox and even incoming requests by my orderer3 over longer time.
```
2021/11/01 18:50:33 [error] 31#31: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 172.21.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:7006", referrer: "http://localhost:7006/",
172.21.0.1 - - [01/Nov/2021:18:50:33 +0000] "GET /favicon.ico HTTP/1.1" 404 555 "http://localhost:7006/" "Mozilla/5.0 (X11; CrOS armv7l 13597.84.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.98 Safari/537.36" "-",
172.21.0.1 - - [01/Nov/2021:18:51:18 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03c\x0E\xA1\xF9\xE6\xC5\x1Dtj\xFAn\xCE\xA9\x1E\x1E\xAD\xD2\xDF\xCBRF\xE3\xC0Q\x0C\x15\x88\xC2Tb\x01\xA3 bS\x91\xF2\x86\x99\xAD" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:52:30 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03\x94\x09\xE7\xE7\xBB-\xDA\xBB\xD0\xF8\xD7pfq\xD1\xC5$\x02\xAE.\xB2\xC8\xA9\xDB\x14|t\x96h\xAC\xF0x \x05\xDD\xDC2,*{\x1E\x04lv\xCE`" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:52:31 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03a\xE1i^v\x7F\x04\xB1\xCD#\x94\x05!\xE1\xDEH\xB2P\x92M4Ym\x1D!7\x11\x1EF\xBD\xF8\x0E \xFB`\xDC\x7FP\xC6\xDF\x88=\xF5\x1E\xEA\x03\xF9\xFEe\xF9\xDEC\xB3\xA6\x8D\x09f)\xEB$\x86\xF6\xFA\xE3t\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:52:33 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03h7\x12\xA4\xB7\xDB(Po;\xE2\x05\xDBE\xA4\xB0\xB83'\xD3" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:52:35 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03\xC00]\xC3m\xC2f0[|r)\xFE\xEA\xD6\xCC\x04\x03\x85\xB4\xEF\xEE\xA7X\xE8M\xD0N\xF9wO\xC7 \xE2\xC2|7" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:53:21 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03\xDA\xAD\x7F\x8F\xD6\x0F\x0F\xBA\xC2\x1B\xD3\x89\xB3\xEDz/\xC3i\xC4I\x9Cb<\xAC\xE9O!4\x8C\xDE\x8A\xF5 (\x89\x8Fc\x86$\xFDf\x06\x00X\xFD\xC8\xDE\x9F\xE5\xE3\xDA\x90\x0B\xBF=U\xCF\x17 8\x8C\xA1\x1B)\x89\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:55:09 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03\x06\xF2b\xF8\x10\xFB\xBAU\xB7\xC4\x99\xAFw\xFC\xAE}\xF5\xD3\xB4\xAE\xC5{J\x98G\x93\xB91\x13\x12;\xEE \xBA\xAA\x7Fy\xE9A\xC1n\xEA\xFB\xBCV`O\xAC+\xB7\xC8N5>\x1D\xF5}H\xE64o\x9A\xDD\x16\xA9\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:57:14 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03;\x91\x11\x9B\x11:\x92F\xA4O\xBA\x80\x14\xF9,\xC0\xA1j\x11\xE2\x19\x9Ar4\x1C\x05\xE1\xC5l\x86v\x0F \xF4p4uu\xD2\xF9\x5C\xEC\x1A\x97\x19#q++\x93\xEAw\xD2\xBE\x07\x84\x83\xDD\xFF\x07\x9B~\xD7KX\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:18:59:11 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03\xE9,\x08k\x97R\xF9\xFC7\x0F\xD9cwB\xAC\xD6\x87h\xA00\x93\xBDF\x96\xAC\xB5e\xE6\x9AN\xC8\xE2 \xE4?\xF3sn}Z\xF5y\x0E\x10\xF8B_\x97\xD7:]\xBA\x1E\xCC\x89r\xF1\x91\x81\xBB\xE9\x80:\x1Cg\x00&\xCC\xA8\xCC\xA9\xC0/\xC00\xC0+\xC0,\xC0\x13\xC0\x09\xC0\x14\xC0" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:19:00:53 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03B\xF1\xDAq\xB8Znv\xB7\x9E\xEA\x11\xFE\x8E\x8C?\x9Ce\x82\xA9'\xEADJ/" 400 157 "-" "-" "-",
172.21.0.1 - - [01/Nov/2021:19:02:35 +0000] "\x16\x03\x01\x00\xF3\x01\x00\x00\xEF\x03\x03?\xE1\xE2 S\xF0\x93Tri\xAAu\xBD`S" 400 157 "-" "-" "-"
```

**Comment by Tobias263** [comment]
Good evening!

I am working with @CodingSinceThe80s and @KSilkThread on the problem described above and would like to give a short update on our progress.

The segmentation error occurs when calling the function "atomic.storeInt64()"
(https://github.com/hyperledger/fabric/blob/v2.2.0/gossip/identity/identity.go#L261) and we suspect that this is related to the problem described here (https://github.com/golang/go/issues/23345#issuecomment-427592439).

So we changed the operating system to raspios-bullseye-arm64 and tried again. With this configuration and some small adjustments (like a missing jq installation in the cli container) we had success and were able to run minifabric.

Currently we are running a multi-host network with 5 Raspberry Pi's and our own Java chaincode. So far we can't detect any other problems.

If it is fine for you, we would leave the issue open and report here about further steps.

Thanks for your help @litong01

**Comment by litong01** [comment]
@Tobias263 This is great news. Very happy that you were able to get things going on ARM. It will be super nice if you create a small document in docs directory to outline few important things that one needs to take to get things working on ARM environment.

**Comment by KSilkThread** [comment]
Happy new year @litong01 ! Following the PR on our latest findings. https://github.com/hyperledger-labs/minifabric/pull/320
