### ISSUE TITLE
minifab error when try up 2.3.3 fabric

### ISSUE THREAD

**Issue by ZoomQuiet** [hyperledger-labs/minifabric#300]
$ minifab up -i 2.3.3
```
    ...
    Minifab Execution Context:
        FABRIC_RELEASE=2.3.3
        CHANNEL_NAME=myccchannel
        PEER_DATABASE_TYPE=golevel
        CHAINCODE_LANGUAGE=go
        CHAINCODE_NAME=simple
        CHAINCODE_VERSION=3.0
        CHAINCODE_INIT_REQUIRED=true
        CHAINCODE_PARAMETERS="query","a"
        CHAINCODE_PRIVATE=false
        CHAINCODE_POLICY=
        TRANSIENT_DATA=
        BLOCK_NUMBER=0
        EXPOSE_ENDPOINTS=false
        CURRENT_ORG=org0.example.com
        HOST_ADDRESSES=178.128.91.32,10.15.0.5,10.104.0.2
        WORKING_DIRECTORY: /opt/proj/minifab
    .......
    # Preparing for the following operations: *********************
    verify options, download images, generate certificates, start network, network status, channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
    .......


    # Docker node status ******************************************
    mysite : Up 15 seconds
    ca1.org1.example.com : Up 18 seconds
    ca1.org0.example.com : Up 20 seconds
    orderer3.example.com : Up 23 seconds
    orderer2.example.com : Up 25 seconds
    orderer1.example.com : Up 28 seconds
    peer2.org1.example.com : Up 31 seconds
    peer1.org1.example.com : Up 33 seconds
    peer2.org0.example.com : Up 36 seconds
    peer1.org0.example.com : Up 38 seconds

    # Fabric network peer and orderer node health status **********
    peer1.org0.example.com "OK"
    peer2.org0.example.com "OK"
    peer1.org1.example.com "OK"
    peer2.org1.example.com "OK"
    orderer1.example.com "OK"
    orderer2.example.com "OK"
    orderer3.example.com "OK"
    Network Status: 100%

    # Running operation: ******************************************
    channel create
    ......
    # Running operation: ******************************************
    channel join
    ...........................
    # Running operation: ******************************************
    anchor update
    ............
    # Running operation: ******************************************
    profile generation
    .................................
    # Running operation: ******************************************
    cc install
    ...........................
    # Running operation: ******************************************
    cc approve
    ......
    # Running operation: ******************************************
    cc commit
    ..............
    # Running operation: ******************************************
    cc initialize
    .....
    # Run the chaincode instantiate script on cli container *******
    non-zero return code
    Error: endorsement failure during invoke. response: status:500 message:"error in simulation: transaction returned with failure: Incorrect number of arguments. Expecting 4"

    # STATS *******************************************************
    minifab: ok=232 failed=1

    real    9m33.835s
    user    1m58.377s
    sys     0m24.440s
```

my ENV.

```
$ screenfetch
                          ./+o+-       zoomq@ubuntu-s-1vcpu-2gb-sgp1-01
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.4.0-89-generic
           .++ .:/++++++/-.+sss/`      Uptime: 22h 32m
         .:++o:  /++++++++/:--:/-      Packages: 1153
        o:+o+:++.`..```.-/oo+++++/     Shell: bash 5.0.17
       .:+o:+o/.          `+sssoo+/    Disk: 13G / 149G (9%)
  .++/+:+oo+o:`             /sssooo.   CPU: DO-Premium-Intel @ 2x 2.494GHz
 /+++//+:`oo+o               /::--:.   RAM: 993MiB / 1987MiB
 \+/+o+++`o++o               ++////.
  .++.o+++oo+:`             /dddhhh.
       .+.o+oo:.          `oddhhhh+
        \+.++o+o``-````.:ohdhhhhh+
         `:o+++ `ohhhhhhhhyo++os:
           .o:`.syhhhhhhh/.oo++o`
               /osyyyyyyo++ooo+++/
                   ````` +oo+++o\:
                          `oo++.

```

$ curl --version
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets

$ git --version
git version 2.25.1

$ docker --version
Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2

$ jq --version
jq-1.5-1-a5b5cbe

$ go version
go version go1.17.2 linux/amd64

and hand first installed fabric-sample-test-network;
usage
> $ curl -sSL https://bit.ly/2ysbOFE | bash -s -- 2.3.3 1.5.2

can running all nedd docker:

**Comment by itaru2622** [comment]
@ZoomQuiet I think it is not caused by fabric ver 2.3.3.
according to your log, 

> CHAINCODE_PARAMETERS="query","a"

This should be below in case of "minifab up"

CHAINCODE_PARAMETERS="init","a","200","b","300"

that is "init" method with four args.

I guess you executed minifab up before cleanup old fabric network.
so, first cleanup as below, then try again. 
```
minifab cleanup
```

**Comment by ZoomQuiet** [comment]
@itaru2622 囧rz... that is realy key config option;

retry:

/opt/proj/minifab
$ minifab up -i 2.3.3
Using default spec file
Minifab Execution Context:
    FABRIC_RELEASE=2.3.3
    CHANNEL_NAME=mychannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=simple
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","300"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=178.128.91.32,10.15.0.5,10.104.0.2
    WORKING_DIRECTORY: /opt/proj/minifab
.......
# Preparing for the following operations: *********************
  verify options, download images, generate certificates, start network, network status, channel create, channel join, anchor update, profile generation, cc install, cc approve, cc commit, cc initialize, discover
..................


# Running operation: ******************************************
  cc initialize
......
# Running operation: ******************************************
  discover
........................
# Discover endorsers results **********************************
  Chaincode endorsers file: ./vars/discover/mychannel/simple_endorsers.json
# Discover orderers results ***********************************
  Channel orderers file: ./vars/discover/mychannel/ordererendpoints.json

# STATS *******************************************************
minifab: ok=424 failed=0

real    7m37.898s
user    3m28.003s
sys     0m57.582s


right, that is all OK

thanx for suggest.

minifab is so cool.
