### ISSUE TITLE
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed

### ISSUE THREAD

**Issue by ssaha7714** [hyperledger-labs/minifabric#314]
I am using docker version 20.10.8 in my macbook pro. 

xxxx@WKMZTZQ1E459 mywork % docker -v
Docker version 20.10.8, build 3967b7d
xxxx@WKMZTZQ1E459 mywork %

When running ./minifab up, I am getting the following error:

# Run the chaincode install script on cli container ***********
  non-zero return code
  go: downloading github.com/hyperledger/fabric v1.4.1
  go: downloading github.com/spf13/viper v1.7.1
  go: downloading github.com/golang/protobuf v1.3.3
  go: downloading google.golang.org/grpc v1.31.1
  go: downloading github.com/pkg/errors v0.9.1
  go: downloading go.uber.org/zap v1.15.0
  go: downloading github.com/pelletier/go-toml v1.2.0
  go: downloading github.com/spf13/afero v1.1.2
  go: downloading github.com/spf13/cast v1.3.0
  go: downloading github.com/mitchellh/mapstructure v1.1.2
  go: downloading golang.org/x/net v0.0.0-20200822124328-c89045814202
  go: downloading gopkg.in/yaml.v2 v2.3.0
  go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
  go: downloading github.com/op/go-logging v0.0.0-20160315200505-970db520ece7
  go: downloading golang.org/x/text v0.3.2
  go: finding module for package github.com/miekg/pkcs11
  go: downloading go.uber.org/atomic v1.6.0
  go: downloading gopkg.in/ini.v1 v1.51.0
  go: downloading github.com/subosito/gotenv v1.2.0
  go: downloading github.com/grpc-ecosystem/go-grpc-middleware v1.2.1
  go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
  go: downloading github.com/hashicorp/hcl v1.0.0
  go: downloading github.com/sykesm/zap-logfmt v0.0.3
  go: downloading github.com/spf13/pflag v1.0.3
  go: downloading go.uber.org/multierr v1.5.0
  go: downloading google.golang.org/genproto v0.0.0-20200423170343-7949de9c1215
  go: downloading github.com/fsnotify/fsnotify v1.4.7
  go: downloading github.com/spf13/jwalterweatherman v1.0.0
  go: downloading github.com/miekg/pkcs11 v1.0.3
  go: downloading github.com/magiconair/properties v1.8.1
  go: downloading github.com/fsouza/go-dockerclient v1.6.5
  go: downloading github.com/hyperledger/fabric-amcl v0.0.0-20200424173818-327c9e2cf77a
  go: downloading github.com/docker/docker v1.4.2-0.20191101170500-ac7306503d23
  go: downloading github.com/Microsoft/go-winio v0.4.15-0.20200113171025-3fe6c5262873
  go: downloading github.com/docker/go-units v0.4.0
  go: downloading github.com/docker/go-connections v0.4.0
  go: downloading github.com/containerd/continuity v0.0.0-20200228182428-0f16d7a0959c
  go: downloading github.com/gogo/protobuf v1.3.1
  go: downloading github.com/containerd/containerd v1.3.0
  go: downloading github.com/opencontainers/image-spec v1.0.1
  go: downloading github.com/opencontainers/runc v0.1.1
  go: downloading github.com/sirupsen/logrus v1.4.2
  go: downloading github.com/morikuni/aec v1.0.0
  go: downloading github.com/Microsoft/hcsshim v0.8.7
  go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
  go: downloading github.com/Azure/go-ansiterm v0.0.0-20170929234023-d6e3b3328b78
  go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
  go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
  go: downloading github.com/docker/distribution v2.7.1+incompatible
  go: found github.com/miekg/pkcs11 in github.com/miekg/pkcs11 v1.0.3
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get "http://unix.sock/images/dev-peer1.org0.example.com-simple_1.0-bb0642f7184041106dc3c495de384d3f4788ada0639be92b561461b35edffb67-7821bed4419d0df065d2627a604d7dae23d96ef012bff2b4115469327f0b87aa/json": dial unix /host/var/run/docker.sock: connect: no such file or directory

# STATS *******************************************************
minifab: ok=327	failed=1	

Please let me know how to fix this..

@litong01

**Comment by litong01** [comment]
You need to disable the docker desktop experimental feature. This is known issue. Please search the closed issues on this.

**Comment by litong01** [comment]
Basically do this

unchecked gRPC FUSE from docker desktop settings 

Please close this issue.

**Comment by ssaha7714** [comment]
Thanks @litong01 , unchecking gRPC FUSE  solved my problem.
