### ISSUE TITLE
Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction 7e04a449d757e86b2b4a1dc0fc752f5670d15f00c28fe20efefef6facb7b641e: invalid invocation: chaincode 'myccc' has not been initialized for this version, must call as init first"

### ISSUE THREAD

**Issue by ssaha7714** [hyperledger-labs/minifabric#315]
I have installed minifabric. Followed the command mention in the github readme. I am able to query with existing channel. 

I created a channel coolchannel. 

Then, I copied the **simple** chaincode and created another one with name **myccc**. I ran the following command.
1. ./minifab install -n myccc -l go -p '"init","a","200","b","100"'
2. ./minifab approve
3. ./minifab commit
4. ./minifab discover 
It was successful. Logs below:
`xxxx@WKMZTAA2E459 mywork % ./minifab discover                                              
Using spec file: /Users/swasaha/mywork/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=coolchannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=myccc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="init","a","200","b","100"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.5,10.102.218.154
    WORKING_DIRECTORY: /Users/swasaha/mywork
.......
# Preparing for the following operations: *********************
  verify options, discover
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  discover
........................
# Discover endorsers results **********************************
  Chaincode endorsers file: ./vars/discover/coolchannel/myccc_endorsers.json
# Discover orderers results ***********************************
  Channel orderers file: ./vars/discover/coolchannel/ordererendpoints.json

# STATS *******************************************************
minifab: ok=47	failed=0	

real	0m15.246s
user	0m12.448s
sys	0m3.402s
xxxx@WKMZTAA2E459 mywork %`

5. ./minifab invoke -p '"query","a"'
Log message:
`xxxx@WKMZTAA2E459 mywork % ./minifab invoke -p '"query","a"'                               
Using spec file: /Users/swasaha/mywork/spec.yaml
Minifab Execution Context:
    FABRIC_RELEASE=2.3.0
    CHANNEL_NAME=coolchannel
    PEER_DATABASE_TYPE=golevel
    CHAINCODE_LANGUAGE=go
    CHAINCODE_NAME=myccc
    CHAINCODE_VERSION=1.0
    CHAINCODE_INIT_REQUIRED=true
    CHAINCODE_PARAMETERS="query","a"
    CHAINCODE_PRIVATE=false
    CHAINCODE_POLICY=
    TRANSIENT_DATA=
    BLOCK_NUMBER=newest
    EXPOSE_ENDPOINTS=false
    CURRENT_ORG=org0.example.com
    HOST_ADDRESSES=192.168.1.5,10.102.218.154
    WORKING_DIRECTORY: /Users/swasaha/mywork
.......
# Preparing for the following operations: *********************
  verify options, cc invoke
.......
# Running operation: ******************************************
  verify options
.
# Running operation: ******************************************
  cc invoke
..............
# Run the chaincode invoke script on cli container ************
  non-zero return code
  Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction 9321b5bc6124267326ace94c4f944b23f51134bdb4a768ae63dfec108a5c7ccd: **invalid invocation: chaincode 'myccc' has not been initialized for this version, must call as init first**"

# STATS *******************************************************
minifab: ok=33	failed=1	

real	0m8.327s
user	0m6.924s
sys	0m1.510s
xxxx@WKMZTAA2E459 mywork % `

I thought I need to invoke init first, so I tried the following
6. xxxx@WKMZTAA2E459 mywork % ./minifab invoke -p '"init","a","200","b","100"'
But no success, it is also giving me the same error.

`# Run the chaincode invoke script on cli container ************
  non-zero return code
  Error: endorsement failure during invoke. response: status:500 message:"error in simulation: failed to execute transaction 7e04a449d757e86b2b4a1dc0fc752f5670d15f00c28fe20efefef6facb7b641e: invalid invocation: chaincode 'myccc' has not been initialized for this version, must call as init first"

# STATS *******************************************************
minifab: ok=33	failed=1	

`

I am stuck. @litong01  can you please help me what I am doing wrong? 
Note: I am a beginner. Hence in need of help.

**Comment by litong01** [comment]
You need to initialize the chaincode as the error said. So try minifab initialize command before you call invoke.

**Comment by ssaha7714** [comment]
Thanks @litong01  . Closing this issue :) 
./minifab initialize -p '"init","a","200","b","100"' solves the issue.
