### ISSUE TITLE
Question: define endorsement policies of chaincode being installed.

### ISSUE THREAD

**Issue by nikolas-digitalBabylon** [hyperledger-labs/minifabric#316]
Hi,

I am missing in the documentation any info regarding defining endorsing policies of installed chaincode. I would appreciate any examples or hints. Are there any parameters that can be set when running the minifab ccup command to define the endorsement policies?

Thanks.

**Comment by litong01** [comment]
Use -h to see all options. There is one option to set policy. Please ask your question in rocket chat channel and close this one.

**Comment by nikolas-digitalBabylon** [comment]
Thanks, I am aware of the option. My question is more about how it is actually used, as I did not find relevant documentation. It is not clear if the argument in command line should be like `"AND('Org1.peer', 'Org2.peer')"` or something else. 
Anyhow, i close the topic.

**Comment by litong01** [comment]
The syntax must be the same as the official document states.
