### ISSUE TITLE
Multi cloud setup for minifabric failing

### ISSUE THREAD

**Issue by ssaha7714** [hyperledger-labs/minifabric#317]
Hi @litong01 ,
I am trying to set up multi cloud(AWS and Azure) using minifabric. I performed the following steps to achieve the goal.
 
In Azure VM (which has private IP 10.0.0.6 and public IP 40.114.38.190 ), I created one spec file as below
fabric:
  cas:
  - "ca1.org0.example.com"
  peers:
  - "peer1.org0.example.com"
  - "peer2.org0.example.com"
  orderers:
  - "orderer1.example.com"
  - "orderer2.example.com"
  - "orderer3.example.com"
  settings:
    ca:
      FABRIC_LOGGING_SPEC: DEBUG
    peer:
      FABRIC_LOGGING_SPEC: DEBUG
    orderer:
      FABRIC_LOGGING_SPEC: DEBUG
  netname: "ps"

I have executed the following commands one by one:

`
minifab up -e 7778`
`minifab channelquery`
`minifab profilegen`

In AWS EC2 (which has private IP - 172.31.26.250 and public IP - 54.174.233.205 ) I created a spec file as below

`fabric:
  peers: 
  - "peer1.org3.ps.com"
  - "peer2.org3.ps.com"`

I then ran the following command:

`minifab netup -e true -o org3.ps.com
`

From Azure VM, I copied the file endpoints.yaml and changed the presence of private IP address 10.0.0.6 to public IP address 40.114.38.190 as shown below.

`
"ordererEndpoints":
  - "fullname": "orderer1.example.com"
    "mspid": "example-com"
    "name": "orderer1"
    "url": "40.114.38.190"
    "port": "7781"
    "org": "example.com"
    "type": "orderer"
    "tlsCACerts": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvakNDQWtpZ0F3SUJBZ0lVRnJURkd6bndkNVZQM2tjNzV3QTE2b2dwZmxrd0NnWUlLb1pJemowRUF3SXcKYWpFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ01EazV2Y25Sb0lFTmhjbTlzYVc1aE1SQXdEZ1lEVlFRSApEQWRTWVd4bGFXZG9NUlF3RWdZRFZRUUtEQXRsZUdGdGNHeGxMbU52YlRFYU1CZ0dBMVVFQXd3UmRHeHpZMkV1ClpYaGhiWEJzWlM1amIyMHdIaGNOTWpJd01UQTFNVFF3T1RRNFdoY05Nekl3TVRBek1UUXdPVFE0V2pCcU1Rc3cKQ1FZRFZRUUdFd0pWVXpFWE1CVUdBMVVFQ0F3T1RtOXlkR2dnUTJGeWIyeHBibUV4RURBT0JnTlZCQWNNQjFKaApiR1ZwWjJneEZEQVNCZ05WQkFvTUMyVjRZVzF3YkdVdVkyOXRNUm93R0FZRFZRUUREQkYwYkhOallTNWxlR0Z0CmNHeGxMbU52YlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktpZ0tmNFJPMCs0QlNGRjdsckoKY00zdHphcFF4aEd3NHlmT1U4NjQvdVBSdkw2MTJMbGhUOTNjNi9qMGtXSWlzc1dJemYwbjhPR05KNWorNUJ1dApIa1NqZ2Nzd2djZ3dIUVlEVlIwT0JCWUVGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUI4R0ExVWRJd1FZCk1CYUFGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFAKQVFIL0JBUURBZ0dtTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQkdCZ05WSFJFRQpQekE5aHdRS0FBQUdnaEYwYkhOallTNWxlR0Z0Y0d4bExtTnZiWUlSZEd4elkyRXRaWGhoYlhCc1pTMWpiMjJDCkNXeHZZMkZzYUc5emRJY0Vmd0FBQVRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXMxVW1HUVZ2OXE2c0ZSTWwKMk1kYUMzRTZrWEZFTFM4RjNwQ0V2WTBGN25JQ0lERE1Jc3NMV3lkYTNadVc4ZjRMYit3bnY2bm1UOGJoSERMdQpZdjUxOHkvRQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
  - "fullname": "orderer2.example.com"
    "mspid": "example-com"
    "name": "orderer2"
    "url": "40.114.38.190"
    "port": "7782"
    "org": "example.com"
    "type": "orderer"
    "tlsCACerts": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvakNDQWtpZ0F3SUJBZ0lVRnJURkd6bndkNVZQM2tjNzV3QTE2b2dwZmxrd0NnWUlLb1pJemowRUF3SXcKYWpFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ01EazV2Y25Sb0lFTmhjbTlzYVc1aE1SQXdEZ1lEVlFRSApEQWRTWVd4bGFXZG9NUlF3RWdZRFZRUUtEQXRsZUdGdGNHeGxMbU52YlRFYU1CZ0dBMVVFQXd3UmRHeHpZMkV1ClpYaGhiWEJzWlM1amIyMHdIaGNOTWpJd01UQTFNVFF3T1RRNFdoY05Nekl3TVRBek1UUXdPVFE0V2pCcU1Rc3cKQ1FZRFZRUUdFd0pWVXpFWE1CVUdBMVVFQ0F3T1RtOXlkR2dnUTJGeWIyeHBibUV4RURBT0JnTlZCQWNNQjFKaApiR1ZwWjJneEZEQVNCZ05WQkFvTUMyVjRZVzF3YkdVdVkyOXRNUm93R0FZRFZRUUREQkYwYkhOallTNWxlR0Z0CmNHeGxMbU52YlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktpZ0tmNFJPMCs0QlNGRjdsckoKY00zdHphcFF4aEd3NHlmT1U4NjQvdVBSdkw2MTJMbGhUOTNjNi9qMGtXSWlzc1dJemYwbjhPR05KNWorNUJ1dApIa1NqZ2Nzd2djZ3dIUVlEVlIwT0JCWUVGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUI4R0ExVWRJd1FZCk1CYUFGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFAKQVFIL0JBUURBZ0dtTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQkdCZ05WSFJFRQpQekE5aHdRS0FBQUdnaEYwYkhOallTNWxlR0Z0Y0d4bExtTnZiWUlSZEd4elkyRXRaWGhoYlhCc1pTMWpiMjJDCkNXeHZZMkZzYUc5emRJY0Vmd0FBQVRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXMxVW1HUVZ2OXE2c0ZSTWwKMk1kYUMzRTZrWEZFTFM4RjNwQ0V2WTBGN25JQ0lERE1Jc3NMV3lkYTNadVc4ZjRMYit3bnY2bm1UOGJoSERMdQpZdjUxOHkvRQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
  - "fullname": "orderer3.example.com"
    "mspid": "example-com"
    "name": "orderer3"
    "url": "40.114.38.190"
    "port": "7783"
    "org": "example.com"
    "type": "orderer"
    "tlsCACerts": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNvakNDQWtpZ0F3SUJBZ0lVRnJURkd6bndkNVZQM2tjNzV3QTE2b2dwZmxrd0NnWUlLb1pJemowRUF3SXcKYWpFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ01EazV2Y25Sb0lFTmhjbTlzYVc1aE1SQXdEZ1lEVlFRSApEQWRTWVd4bGFXZG9NUlF3RWdZRFZRUUtEQXRsZUdGdGNHeGxMbU52YlRFYU1CZ0dBMVVFQXd3UmRHeHpZMkV1ClpYaGhiWEJzWlM1amIyMHdIaGNOTWpJd01UQTFNVFF3T1RRNFdoY05Nekl3TVRBek1UUXdPVFE0V2pCcU1Rc3cKQ1FZRFZRUUdFd0pWVXpFWE1CVUdBMVVFQ0F3T1RtOXlkR2dnUTJGeWIyeHBibUV4RURBT0JnTlZCQWNNQjFKaApiR1ZwWjJneEZEQVNCZ05WQkFvTUMyVjRZVzF3YkdVdVkyOXRNUm93R0FZRFZRUUREQkYwYkhOallTNWxlR0Z0CmNHeGxMbU52YlRCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQktpZ0tmNFJPMCs0QlNGRjdsckoKY00zdHphcFF4aEd3NHlmT1U4NjQvdVBSdkw2MTJMbGhUOTNjNi9qMGtXSWlzc1dJemYwbjhPR05KNWorNUJ1dApIa1NqZ2Nzd2djZ3dIUVlEVlIwT0JCWUVGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUI4R0ExVWRJd1FZCk1CYUFGSzZKZ1Z2QkwrWXhRL21RbkZiTTNQdWlzWFhpTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RGdZRFZSMFAKQVFIL0JBUURBZ0dtTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQkdCZ05WSFJFRQpQekE5aHdRS0FBQUdnaEYwYkhOallTNWxlR0Z0Y0d4bExtTnZiWUlSZEd4elkyRXRaWGhoYlhCc1pTMWpiMjJDCkNXeHZZMkZzYUc5emRJY0Vmd0FBQVRBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlFQXMxVW1HUVZ2OXE2c0ZSTWwKMk1kYUMzRTZrWEZFTFM4RjNwQ0V2WTBGN25JQ0lERE1Jc3NMV3lkYTNadVc4ZjRMYit3bnY2bm1UOGJoSERMdQpZdjUxOHkvRQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
`

I transferred this file into AWS EC2 and placed under /vars/

Then I ran the following commands:

`
minifab nodeimport`
`sudo docker ps --format "{{.Names}}:{{.Ports}}"
`

Able to see the docker containers.

Then I copied the content of JoinRequest_org3-ps-com.json and updated the file mychannel_config.json in Azure VM. Also updated the version number to 2.

Then ran the following command in Azure VM. 

`minifav channelsign,channelupdate`

In AWS EC2, I ran the following 

`minifab install`

It was successful.

I ran the following command

`minifab join -c mychannel`

and I received the following error.

`.......
# Run the channel join script on cli container ****************
  non-zero return code
  2022-01-05 14:03:05.268 UTC [comm.tls] ClientHandshake -> ERRO 001 Client TLS handshake failed after 3.00863ms with error: x509: certificate is valid for 10.0.0.6, 127.0.0.1, not 40.114.38.190 remoteaddress=40.114.38.190:7781
  2022-01-05 14:03:06.275 UTC [comm.tls] ClientHandshake -> ERRO 002 Client TLS handshake failed after 4.165421ms with error: x509: certificate is valid for 10.0.0.6, 127.0.0.1, not 40.114.38.190 remoteaddress=40.114.38.190:7781
  2022-01-05 14:03:07.570 UTC [comm.tls] ClientHandshake -> ERRO 003 Client TLS handshake failed after 4.72495ms with error: x509: certificate is valid for 10.0.0.6, 127.0.0.1, not 40.114.38.190 remoteaddress=40.114.38.190:7781
  Error: failed to create deliver client for orderer: orderer client failed to connect to 40.114.38.190:7781: failed to create new connection: context deadline exceeded
  2022-01-05 14:03:08.318 UTC [channelCmd] InitCmdFactory -> INFO 001 Endorser and orderer connections initialized
  Error: genesis block file not found open /vars/mychannel.genesis.block: no such file or directory

# STATS *******************************************************
minifab: ok=28	failed=1	

real	0m10.480s
user	0m6.849s
sys	0m1.292s`

May be I am missing something from the documentation or something I need to do to make it work with multi VM having public and private IP. 

@litong01  Please help.

**Comment by webzest** [comment]
Hi @litong01.  
I am having a similar issue or requirement for a Google cloud setup.  Trying to build a multi VM decentralized network.  I am able to build a single VM with multiple peers and orderers, but I need help getting them to talk to each other over the different locations.   I did  call minifab with -e 7900 and my network completed successful on the first VM.  Would you please help us to do this?  You probably did this already and have a solution.  I am sure we are not the first developers to ask this question.  Thank you for your understanding and support.  IBM is GREAT!

**Comment by litong01** [comment]
Do not have aws access to recreate your issue. It seems to me that you may have to move the genesis block to the right folder.

**Comment by webzest** [comment]
Hello Tong,

 

Sounds good.  I wish I knew which folder and which image to move it to on minifabric.

Please try building a decentralized network with 3 machines,  one single org, 3 peers, two channels, 1 CA, and one Orderer per channel.  You do not need to have access to AWS or Google cloud.   Then, try to get them to talk to each other and install chaincode to the channels.  Se if that works for you…  

 

Best Regards,

 




 

 <https://www.linkedin.com/in/johnnysandaire/>    <https://twitter.com/JohnnySandaire> 

Johnny Sandaire PhD, PMP, MCAD
VP Technology Integration @  <https://cleararmor.com/> ClearArmor, LLC

Owner @ WebZest, LLC

Johnny Sandaire Photography

 

Email:  ***@***.***> ***@***.*** 

Phone: (908) 377-3627

 

570 South Ave East, Cranford, NJ  07016

 <http://www.johnnysandaire.com/> www.johnnysandaire.com   <http://www.webzest.com/> www.webzest.com

**Comment by ssaha7714** [comment]
I am able to solve this particular issue (as mentioned in my original question) hence closing this issue. Thanks @litong01  for your help. I am facing another issue. Might be I will create a new issue (different one) mentioning the steps I followed.
