### ISSUE TITLE
Problem to join a third organization

### ISSUE THREAD

**Issue by LeoGCRocha** [hyperledger-labs/minifabric#328]
Following the tutorial present in the hyperledger fabric documentation(Expand your network), I was able to correctly perform the first organization's ingress stage, including perfect operation in the use of chaincodes. However, I'm having trouble joining the third organization, where the following error is returned: "Chaincode definition not agreed to this org (org2.br)". How can I integrate a third organization to my network?

Ps: Each organization is in a different machine.

**Comment by rupam150** [comment]
Hi @LeoGCRocha  how did you solved it , is there any specific rules for approval process of chaincode , Please help me in this , as i am stuck from days on this , Please provide the steps for connecting 3 org in the channel procedure
