### ISSUE TITLE
i/o timeout when I run ./minifab up

### ISSUE THREAD

**Issue by knight-hjh** [hyperledger-labs/minifabric#334]
![image](https://user-images.githubusercontent.com/38315608/163781171-90aec65a-6aa2-45ad-817e-12354d6de779.png)
I have install the go
![image](https://user-images.githubusercontent.com/38315608/163781239-26bd46d1-f81d-47da-919f-67645a798231.png)
The docker images are:
![image](https://user-images.githubusercontent.com/38315608/163781265-58324637-df4d-49df-9231-74c8dde2b283.png)
I also use the following commands to change the proxy:
go env -w GOPROXY=https://goproxy.io,direct
go env -w GO111MODULE=on

Maybe this is a simple question :(

**Comment by litong01** [comment]
If you are in an area which google sites are blocked, you need to point your system into an alternative site for your go dependency to be satisfied. Use a correct proxy endpoint as you have already indicated to try, you can actually try the proxy without using minifabric to see if your env can compile go programs.

**Comment by litong01** [comment]
Setup as env won't work for minifabric, you need to specify it in a custom spec.yaml file. Please reference the spec.yaml file and docs.

**Comment by knight-hjh** [comment]
you mean insert a statement like: export GOPROXY = goproxy: "https://goproxy.cn,direct" ??
I have checked the go env. it looks like that 
![image](https://user-images.githubusercontent.com/38315608/163819210-0e68f4c0-3617-49fe-9e85-5630521ace2a.png)
but it still doesn't work out

**Comment by litong01** [comment]
You need to make a copy of the default spec.yaml file and make changes (please look at an example in the comment of that file), then place that file in the directory where you will be running minifab command, that way it will work.

**Comment by knight-hjh** [comment]
I get it. Before, I run minifab directly, so it used the default spec.yaml file. But there are no settings about proxy and endpoint_address in the file. After I configured the proxy, the endpoint_address was set to my server IP address.it will be able to run successfully. Thank you very much.  :)
