### ISSUE TITLE
CouchDB ports expose

### ISSUE THREAD

**Issue by michuer** [hyperledger-labs/minifabric#85]
Is it possible to expose couchDB ports?
After the change of db to couchdb, couchDB's containers are launched for each peer but despite the `EXPOSE_ENDPOINTS=true` do not expose the ports. 

0.0.0.0:7002->7051/tcp         peer1.org0.example.com
4369/tcp, 5984/tcp, 9100/tcp   peer1.org0.example.com.couchdb

**Comment by litong01** [comment]
@michuer That was done on purpose. -e true is to export peer and orderer node ports. If you need to access the db port, you can run your app on the same docker network on which peers and other nodes are running. In my view, that db should not be touched by other apps for various reasons.

**Comment by pkirkinezis** [comment]
For testing purpose . If your goal is to access fauxton  :5984/_utils/ you can do it another way .
Clone a couchdb container instance from minifabric and add it to localhost network. That way you will have access to UI fauxton  of couchdb and also the values of any chaincode you have installed. 
The most easy way to do the above is throuth Portainer. 

But what I have described is for testing and maybe debugging throuth the couchDB UI .
 If you want an app to access couchdb you have to do what @litong01 said.

**Comment by michuer** [comment]
I used an intermediate container to forward the port, which in my case was enough.
A description of how to do this can be found here: https://stackoverflow.com/a/42071577
In addition, the intermediate container must be connected to the minifab network.

**Comment by litong01** [comment]
@michuer so you basically setup a proxy like container to do that, that is quite nice. You may add a doc to the docs directory to show how you can easily do this with a small piece of script, doing that you can help others facing same issue. Please close this issue.

**Comment by pkirkinezis** [comment]
@litong01  also it would be helpfull to inform people about portainer . It can easily help you see container logs . Run commands or check the dokcer network.

**Comment by litong01** [comment]
I will take a look.

**Comment by litong01** [comment]
Portainer is now integrated with minifabric. I will close this issue as there is nothing more need to be done.
