### ISSUE TITLE
Chaincode install fails on ./minifab up

### ISSUE THREAD

**Issue by fnparr** [hyperledger-labs/minifabric#86]
I am running on a Mac with  MacOS/Catalina  10.15.6. with docker  version 19.03.13
installed minicab with: mkdir -p ~/mywork && cd ~/mywork && curl -o minifab -sL https://tinyurl.com/twrt8zv && chmod +x minifab 

added the mywork directory to my path

ran 
  ./minifab down
  ./minifab cleanup 
         to remove any old docker images 
ran
 ./minifab up 
in the install CC  step I get the following error :
  .....
   go: downloading github.com/containerd/continuity v0.0.0-20200228182428-0f16d7a0959c
  go: downloading github.com/opencontainers/runc v0.1.1
  go: downloading github.com/Microsoft/hcsshim v0.8.7
  go: downloading github.com/sirupsen/logrus v1.4.2
  go: downloading golang.org/x/sync v0.0.0-20190423024810-112230192c58
  go: downloading github.com/docker/go-connections v0.4.0
  go: downloading github.com/gogo/protobuf v1.3.1
  go: downloading github.com/opencontainers/go-digest v1.0.0-rc1
  go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.1
  go: downloading github.com/docker/distribution v2.7.1+incompatible
  go: downloading github.com/containerd/containerd v1.3.0
  Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: Get "http://unix.sock/images/dev-peer1.org0.example.com-simple_1.0-909df75bc355cd2e114b0363ef9a4c3d0ccd72df048e8a9c944099cf97c21e9c-c7a9ab2859213ca50480f34a127c17e4d1ff5e7cce0c24d0cea287b2ed47005b/json": dial unix /host/var/run/docker.sock: connect: no such file or directory

# STATS *******************************************************
minifab: ok=335	failed=1

DO you know what is happening ? what might have caused this ? 

It happens that when I try installing  the go chaincode for the  basic (asset transfer) example from  git.com/hyperledger/fabric-samples I also get exactly this same error.   The startup sequence is more complex there.  

@fnparr

**Comment by fnparr** [comment]
There seem to be other users reporting similar issue with HLF  in  https://jira.hyperledger.org/browse/FAB-18134

**Comment by litong01** [comment]
@fnparr were the default simple cc working ok? Try to do "minifab up" and make sure everything is working as expected, then place your chaincode in vars/chaincode/xxxx/go directory, replace xxxx with your chaincode name, then do "minifab install -n xxxx", if you see any errors, that means your chaincode may have not developed correctly.

**Comment by fnparr** [comment]
I was actually working with whatever chain code comes in the download of minifab by default - BUT I think I have found the answer to my problem in: https://github.com/docker/for-mac/issues/4955.  The latest version of docker for Mac must come with gRPC FUSE enabled by default ; I unchecked the box  reverting docker to legacy osxfs file sharing, then cleared all docker state (docker system prune).  After that  ./minifab up works fine and installs the default chain code.

 I really appreciate your responsiveness to my issue.   I will plan to use minifab as I continue to develop and test my chain code following your instructions above. I will also report the discovered workaround to  https://jira.hyperledger.org/browse/FAB-18134 where there may be other fabric-samples Mac users - and no workaround was published there.  I do think that a documentation warning for both minifab and fabric-samples users on Mac could be helpful.

**Comment by litong01** [comment]
Please add some doc in the docs directory on resolve this issue. A PR will be very nice.

**Comment by Jalmeida1994** [comment]
I also have a similar problem, using a _Ubuntu Focal 64bits_ VM on _MacOS_.

`Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image build failed: failed to get layer`
# Stats
`minifab: ok=325 failed=1`

With the default _chaincode_ too. Yesterday was working fine. I'll try @fnparr fix.

**Comment by fnparr** [comment]
joao Carlos  -
Please let me know how that goes - whether your
problem gets resolved  - I plan to write a PR and post into docs on the
minifab site
(hopefully some time today )
if the issue is relevant to a broader class of users on macOS - that should
be noted.

@Francis Parr <fnparr@us.ibm.com>
